### ISSUE TITLE
Why are boto3 and botocore modules included in the deployment package?

### ISSUE THREAD

**Issue by toringe** [aws/chalice#1043]
This [article](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) from the official docs states "_SDK for Python (Boto 3) – 3-1.7.74 botocore-1.10.74_" are included in the underlying AWS Lambda execution environment. So there should be no need to include them in the deployment package.

**Comment by igorborgest** [comment]
Hi @toringe 

Actually Chalice don't inject boto3, botocore neither any other library per default in the deploy package.

That only happens if you explicit the dependencies in the **requirements.txt** file in the root of your Chalice project.
e.g.: `$echo 'boto3==1.3.1' >> requirements.txt`
For more details check the [documentation](https://chalice.readthedocs.io/en/latest/topics/packaging.html#rd-party-packages).

You are right about the lambda environment. The only (and good) reason that I see to add boto3 or botocore to the deploy package is to "freeze" a target version of the libraries and guaranty that unexpected changes will not happen and break your executions.

**Comment by toringe** [comment]
Hi @igorborgest, thanks for the quick reply.

My **requirements.txt** does not contain either boto3 nor botocore:
`$ cat requirements.txt`
> requests==2.21.0
> logzero==1.5.0
> ssm-cache==2.7

However, when I check the deployments files:
`$ unzip -l .chalice/deployments/03576982f00d6cbf0b4d7d9918fde73a-python3.6.zip | grep -i boto`
> 13781  01-09-2019 16:38   botocore/retryhandler.py
> 29815  01-09-2019 16:38   botocore/serialize.py
> 35536  01-09-2019 16:38 botocore/auth.py
> .
> .
> 1576  01-09-2019 16:38   boto3/ec2/createtags.py
> 1163  01-09-2019 16:38   boto3/ec2/deletetags.py

Isn't this the deployment package used when deploying Lambda?

**Comment by igorborgest** [comment]
@tomdyson thanks for more details.

It happens because of **ssm-cache** library.
In a [quick search here](https://github.com/alexcasalboni/ssm-cache-python/blob/master/requirements.txt) I saw that **ssm-cache** has boto3 and botocore as it own dependencies.
So indirectly, you are declaring these libraries as "sub-dependencies" of your project.

Does that make sense for you?

**Comment by toringe** [comment]
Ah, that explains it. Reason I even started looking at this, was because the deploy run took so long to finish due to the relatively large deployment package . Thanks for looking into this!
