### ISSUE TITLE
don't want remove env variables on every deploy (want to deploy only code)

### ISSUE THREAD

**Issue by hkpypy** [aws/chalice#1056]
I have define 2 stages in config.json, one is for dev and other one is for production. I have some critical information like secret keys and api keys which i don't want to hard code in the config.json file. so i leave it blank and want to fill it manually from aws dashboard.
But what happening right now every time when i use chalice deploy it reset all variable again and i have to fill the value every time.
So it there any way by which i can deploy only code?

**Comment by toringe** [comment]
Couldn't you rather put your secrets in e.g Parameter Store, then fetch them from there in your code?

**Comment by tedivm** [comment]
I'd recommend using the secrets manager rather than the parameter store, as the parameter store has much lower throttling limits. According to [this post](https://forums.aws.amazon.com/thread.jspa?messageID=834134&tstart=0) the secrets manager only allows 40 read requests a second, while the [Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_limits.html#reference_limits_rates) allows up to 700 reads per second.

**Comment by stealthycoin** [comment]
Yep agreed with secretsmanager and ssm for secret storage. You can also use KMS encrpyted env variables if you want. In any case you should not be filling them in out-of-band from Chalice. And since chalice deployments have PUT semantics it should be deleting missing ones during a deployment.

**Comment by hkpypy** [comment]
No issue, I have found the work around. you can close this issue. thanks for the help guys. :)
