### ISSUE TITLE
Question: Best practice for multiple lambda

### ISSUE THREAD

**Issue by Sytten** [aws/chalice#1066]
I didn't find a lot of examples with chalice that are more than a `hello world`, so I was wondering what is the best practice for multiple lambdas. I started like I would start with SAM: one function per folder grouped in a single repo for a "service". The code sharing doesn't seem very optimal nor the deployment. Problem is that if you all put them in the same `app.py` I can't seem to find a way to deploy them independently.
Any good practices and more complete examples would greatly appreciated!

**Comment by jamesls** [comment]
The idea with a Chalice app is that it's conceptually one unit.  It all gets deployed at once.  If you want to have different functions deployed independently of each other you'd break them into separate chalice apps.  Otherwise trying to test everything gets complicated, for example if you wanted to test your app locally.  Typically if you're deploying your SAM template through something like codepipeline, all the lambda functions in the template would still get deployed together at the same time.

I'm interested to hear more about your use case/concerns.

**Comment by Sytten** [comment]
Only just beginning in serverless, so I am still adapting to the concepts. I got the feeling that it would probably be considered one app like a microservice but deployed as various lamdas. I started as one app per subfolder, but I am likely switching to one app per repo.

Other unrelated question: is it possible to specify a custom SAM file. It would be useful for triggers that are not supported by Chalice (currently investigating IoT).
