### ISSUE TITLE
Using pure Lambda for API routing

### ISSUE THREAD

**Issue by PapoyEdits** [aws/chalice#1082]
I'm hoping this post doesn't violate guidelines, but I got such a great response on an earlier post, so I'm hedging on that it's okay. 
So I'm developing an API with chalice and am looking to expand functionality into Lambdas outside the main API Lambda. I found that one could use the lambda_function decorator to create a new Lambda and I initially thought this was exactly what I needed, however as I'm now at the point of implementing it, I realize that might not be the case at all. 

Some previous posts here and on StackOverflow have touched upon the subject without coming to a conclusion, but is it possible to use these pure_lambda functions and call them from the API Lambda (for instance to handle database connections to a different tables in RDS)? 
If not, can you accomplish this in another way and not have Everything in the API Lambda?

I really hope that I haven't dug myself into a hole with this, cause I really enjoy using chalice.

**Comment by jamesls** [comment]
Hmm, I'm not entirely sure what you're asking.

>  but is it possible to use these pure_lambda functions and call them from the API Lambda

Are you asking if you can use an SDK/CLI to invoke a lambda function created through Chalice?  If so, yes it's possible.

If you have a link to the stackoverflow questions you were looking at, that might also help.

**Comment by PapoyEdits** [comment]
I'll try to make it a bit clearer.
So my goal is to separate some of the logic/execution from the Lambda that is created to handle the API, to other Lambda functions, preferably defined in the same Chalice project. The flow would be this:
Client calls API in API Gateway -> API calls the API handler Lambda that Chalice creates when deploying -> API Lambda calls another Lambda that is responsible for interacting with a specific database table or performing some task. -> API handler is notified of the completion of the others task and returns a response to the client

[Following the example here](https://chalice.readthedocs.io/en/latest/topics/purelambda.html), for instance, the '/' route would call one of the two extra Lambda functions to perform some work, which upon completion would notify the API Lambda with a status or somehow return for example some rows from the database. 

#229 brings up creating multiple Lambdas in a project and #513 brings up having multiple projects for one API. [This SO post](https://stackoverflow.com/questions/31714788/can-an-aws-lambda-function-call-another) brings up approaches for calling another Lambda, though not in regards to Chalice. 

So, my question is whether one can use the pure lambda from the Chalice docs above to distribute some of the load from the API handler Lambda, and if the approaches in the SO post would allow you to invoke it from the code used for the API handler Lambda. 
Would it then also be possible to return data to the API handler from these extra Lambdas, or can they only perform independent tasks (i.e. only write to the database, but not read and return)? 
If this doesn't work, what other approaches are there for splitting logic between the API handler Lambda and others?

Perhaps my understanding of how an API can be created with the help of Lambdas is mistaken, but it feels odd to have a single Lambda for the entirety of the backend of our system.

**Comment by jamesls** [comment]
Hey, just following on this, I realize it's been a while.

From what I'm understanding, the crux of the issue is to offload work from a single Lambda to multiple lambdas.  The issue that you're going to run into with this is that you can either:

* Invoke another lambda function from the main API Handler lambda, and *block* until it returns a response.
* Invoke another lambda function from the main API Handler asynchronously.  The API Handler will immediately return and the lambda you invoke won't be able to communicate directly back to the API handler.

One alternative you could consider is:

* The main API handler can add work to an SQS queue, and you can use the `@app.on_sqs_message` decorator to process that work in a separate handler.  You'd then have another route you can use to poll for results (you'd put the results somewhere such as DynamoDB).

Let me know if you have any more questions.
