### ISSUE TITLE
Cannot detect proper policy depending on the notation 

### ISSUE THREAD

**Issue by studio3104** [aws/chalice#1088]
Chalice seems not to detect the policy depending on the notation.

Though following implementation sets both `dynamodb:GetItem` and `dynamodb:PutItem` properly,

```python
from chalice import Chalice
import boto3

app = Chalice(app_name='test')
ddb = boto3.client('dynamodb')


@app.route('/')
def index():
    ddb.get_item(...)
    ddb.put_item(...)
    return {'hello': 'world'}
```

this one doesn't.

```python
from chalice import Chalice
import boto3

app = Chalice(app_name='test')
ddb = boto3.resource('dynamodb')
table = ddb.Table(TABLE_NAME)


@app.route('/')
def index():
    table.get_item(...)
    table.put_item(...)
    return {'hello': 'world'}
```

I just tried with only under the following environmental conditions.

```
$ chalice --version
chalice 1.7.0, python 3.6.8, darwin 17.7.0
```

I hope you don't mind this, but could you check it out?

**Comment by kyleknap** [comment]
No worries. Right now the automatic policy generation is only supported through the client interface. We have a tracking GitHub feature request to add resource support for automatic policy generation: https://github.com/aws/chalice/issues/118. This is something we would like to add. I would recommend tracking that GitHub issue for progress.

In the meantime as a workaround, I would recommend utilizing the `gen-policy` command to generate the necessary permissions using client and then add the generated [policy manually](https://chalice.readthedocs.io/en/latest/quickstart.html?highlight=policy#manually-providing-policies) so that you can use the resource interface. Let us know if that helps!
