### ISSUE TITLE
name_prefix being ignored in register_blueprint function

### ISSUE THREAD

**Issue by henry-kr** [aws/chalice#1111]
Hello, from reading blueprints documentation, I understand if I pass name_prefix to register_blueprint, chalice will pre-pend the value of name_prefix to the lambda function it creates. This isn't happening. Only a single lambda function is created with the name of the app.

app.register_blueprint(site_chalice, name_prefix='site-crud')

app.register_blueprint(color_chalice, name_prefix='color-crud')

**Comment by jamesls** [comment]
Sorry for the confusion on this.  The name prefix is used for most lambda functions *except* for the one used with API gateway.  This is because most of the chalice decorators create a new lambda function except for the `@app.route()`.  It's always used a single lambda function for all API gateway routes.  This is why the `name_prefix` is ignored for that function.

There's a feature request to use multiple lambda functions for each route, and if that gets implemented you'd be able to set a prefix for each blueprint.

In the meantime though I'll update the docs to make this more clear.
