### ISSUE TITLE
Need to extend and override with added CORS headers in CognitoUserPoolAuthorizer

### ISSUE THREAD

**Issue by benlvovsky** [aws/chalice#1150]
The source code for CognitoUserPoolAuthorizer I see doesn't make sense how it actually works under the hood. How can I see the actual code, extend and add  CORS headers into response on failing authorization? I understand there is a feature request but I want to do a simple quick fix extending the class. The problem I do not see the logic in available python code. Where does all that logic functionality occur?

**Comment by stealthycoin** [comment]
It doesn't live in python code which is why its not trivial to add support for. Right now we configure API Gateway to handle CORS for us, this gives us the benefit of not invoking a Lambda function, so you don't pay for that lambda runtime. If you wanted to control it yourself and implement behavior that you can't get with the API gateway integration, you would need to disable the built in CORs which uses API Gateway, and write the code yourself in a Chalice route.
