### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by garnaat** [aws/chalice#12]
I don't know if there is anything you can do about this since it is really API Gateway behavior but if you fumble-finger your URL and make the request to an unknown resource, you get:

```
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 42
Content-Type: application/json
Date: Mon, 27 Jun 2016 15:05:22 GMT
Via: 1.1 861b49a34b383ce3ac4ea8b7117b8953.cloudfront.net (CloudFront)
X-Amz-Cf-Id: wfIzVpXxb6UU68XwIgb4P-i4DmfgcbYYOfCMCu4UqJCSI68R3SdkxA==
X-Cache: Error from cloudfront
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amzn-RequestId: 91fd08e2-3c78-11e6-8a68-23416dcaf8cc

{
    "message": "Missing Authentication Token"
}
```

which is kind of confusing.

**Comment by grutty** [comment]
Hi, I used Chalice to deploy a Lambda function and I'm struggling to resolve the error message referenced by @garnaat . 

<pre><code>HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 42
Content-Type: application/json
Date: Wed, 17 Jun 2020 00:17:48 GMT
Via: 1.1 61bc723adb3b1884ed759711e84e13a9.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 7VGHBcaOaG6FtY7zG-hBzJZ-IOgtbAakt95iF9CpD7ElUAWnvenXQA==
X-Amz-Cf-Pop: SEA19-C2
X-Cache: Error from cloudfront
x-amz-apigw-id: OPwe_ErKvHcF5ZA=
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amzn-RequestId: c68ec83f-e660-4737-b57f-3e633546abc4

{
    "message": "Missing Authentication Token"
}
</code></pre>

When I test via AWS CLI I get the above error. When I make the request using Insomnia I get a 500. 

<pre><code>
< HTTP/2 500 
< content-type: application/json
< content-length: 77
< date: Wed, 17 Jun 2020 03:14:34 GMT
< x-amzn-requestid: 8294d263-ff41-4936-bc6a-f50351b8ec63
< x-amz-apigw-id: OQKX9ETRPHcFmNg=
< x-amzn-trace-id: Root=1-5ee98a99-a7101a206bc0983cea761640;Sampled=0
< x-cache: Error from cloudfront
< via: 1.1 4f3feb5c4393987d42d1971d404d7cea.cloudfront.net (CloudFront)
< x-amz-cf-pop: SEA19-C2
< x-amz-cf-id: xRFOhkm-s2nwSjjJhLjQM83dayeD62BjQIA1RH11OjROPjjunZY6DA==
</code></pre>

I can confirm I'm not requesting an unknown resource and that the IAM profile configured using the CLI has sufficient privileges. Is there any documentaiton you can point me to for troubleshooting this? All the docs and responses I've come across deal with using the aws console rather than Chalice.

**Comment by jamesls** [comment]
Can you give me more info or sample code?  You mention you're deploying a lambda function and testing via the AWS CLI but the output you show is output you'd get from making an HTTP request to an API gateway rest API (note the `x-amz-apigw-id` header) which the AWS CLI doesn't support.  Can you show the exact commands you're running to test this lambda function?

**Comment by grutty** [comment]
Thank you for the reply. Yes, to clarify, I misspoke when I said I was testing from AWS CLI. I meant I'm setting my credentials using <code> aws configure </code> then making a request <code>http https://zf4f4g4ssh.execute-api.us-west-2.amazonaws.com/api/ </code> from terminal. I can get a response from the Chalice hello world root path but when I request the path for my Lambda function I get the "missing token" error. 

This is the function:
<pre><code>
import requests, json
from chalice import Chalice

app = Chalice(app_name='alpalca_bot')

API_KEY = '<xxxxxx>'
SECRET_KEY = '<xxxxxxxxxx>'
BASE_URL = "https://paper-api.alpaca.markets"
ORDERS_URL = "{}/v2/orders".format(BASE_URL)
HEADERS = {'APCA-API-KEY-ID': API_KEY, 'APCA-API-SECRET-KEY': SECRET_KEY}

@app.route('/')
def index():
    return {'hello': 'world'}

@app.route('/buy_stonk', methods=['POST'])
def buy_stonk():
    request = app.current_request
    webhook_message = request.json_body

    data = {
    "symbol": webhook_message['ticker'],
    "qty": 1,
    "side": "buy",
    "type": "market",
    "time_in_force": "gtc",
    "order_class": "bracket",
    "take_profit": {
        "limit_price": webhook_message['close'] * 1.035
        },
    "stop_loss": {
        "stop_price": webhook_message['close'] * 0.985,
        }
    }

    r = requests.post(ORDERS_URL, json=data, headers=HEADERS)

    response = json.loads(r.content)

    return {
       'message':'You bought some stonks. Stonks only go up!',
       'webhook_message': webhook_message,
       'id': response['id'],
       'client_order_id': response['client_order_id']
     }
</code></pre>

I redeployed the function with <code>chalice deploy</code> tonight for the nth time, still getting the 403 but this time with some more detail from Cloudfront (below). Based on the "missing token"  error I originally got I've been troubleshooting authentication with my IAM roles and policies but the new message seems to be saying the POST method isn't allowed?  

I'm still unsure on how to resolve in the context of using Chalice and the [quickstart guide](https://github.com/aws/chalice). Thank you again for your help. 

New error messaging after redeploying. 
<pre><code>
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 1053
Content-Type: text/html
Date: Thu, 18 Jun 2020 05:51:08 GMT
Server: CloudFront
Via: 1.1 d6b180eb367f7de26d67a9f3901b96a6.cloudfront.net (CloudFront)
X-Amz-Cf-Id: gydDtVjuL1juvAIRYxzw6aNOLmOw9QvK9yOonnanNNjAPjg2XCKc7A==
X-Amz-Cf-Pop: SEA19-C2
X-Cache: Error from cloudfront

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: gydDtVjuL1juvAIRYxzw6aNOLmOw9QvK9yOonnanNNjAPjg2XCKc7A==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
</code></pre>
