### ISSUE TITLE
Terraform package option should use aws_api_gateway_deployment.lifecycle.create_before_destroy = true

### ISSUE THREAD

**Issue by kislyuk** [aws/chalice#1237]
I am hitting this issue when using `chalice package --pkg-format=terraform`: https://github.com/hashicorp/terraform/issues/10674

The following edit, as suggested in the linked issue, is a successful workaround for me: `jq .resource.aws_api_gateway_deployment.rest_api.lifecycle.create_before_destroy=true chalice.tf.json`

It would be ideal if this code was emitted directly by https://github.com/aws/chalice/blob/a1a8ba0c168cd8980d2a595ece2d0753198fb41a/chalice/package.py#L858-L868.

**Comment by jamesls** [comment]
Do you have a sample chalice app I can try that repros this issue?  I tried it out with a few different examples but wasn't able to generate the BadRequestException

**Comment by kislyuk** [comment]
As noted in https://github.com/hashicorp/terraform/issues/10674, this manifests when using an API Gateway custom domain name with a base path mapping. As I expected, I was unable to trigger this with only vanilla `chalice package --pkg-format=terraform` output. Here are the steps to reproduce:

1. Create and validate an ACM certificate for "chalice-tf-test.MY_VALID_DOMAIN". (As you probably know, this is most easily done if you have a Route53 zone for MY_VALID_DOMAIN and use ACM DNS validation)
2. Run the following, replacing MY_VALID_DOMAIN with the actual value:
```
chalice new-project chalice-tftest
cd chalice-tftest
chalice package --pkg-format terraform .
echo > main.tf <<EOF
data "aws_acm_certificate" "cert" {
  domain       = "chalice-tf-test.MY_VALID_DOMAIN"
}

resource "aws_api_gateway_domain_name" "api_apigwcdn" {
  domain_name = "chalice-tf-test.MY_VALID_DOMAIN"
  certificate_arn = "${data.aws_acm_certificate.cert.arn}"
}

resource "aws_api_gateway_base_path_mapping" "api_bpm" {
  api_id = "${aws_api_gateway_deployment.rest_api.rest_api_id}"
  stage_name = "api"
  domain_name = "chalice-tf-test.MY_VALID_DOMAIN"
}
EOF
terraform init
terraform apply
terraform apply # <-- triggers "Error: error deleting API Gateway Deployment (j7ap14): BadRequestException: Active stages pointing to this deployment must be moved or deleted"
```

**Comment by kapilt** [comment]
interesting, so effectively everything works fine, unless your customizing your chalice deployment to inject in a custom domain mapping. I think it would be nice to support custom domains for apis natively in chalice, given that's a super common user deployment need. Also for customizations, rather than modifying the chalice output, you can just have a separate terraform file in the same directory, as terraform will compute its graph from all the directory (all files ending in tf and tf.json).

I'm trying to understand the implications of create before destroy on the deployment lifecycle, there's some oddities/subtleties to the terraform deployment / rest / stage association that are a little odd (and likely originate from the service's own oddities in that regard), I think originally I had a separate stage but that caused some issues for updates, before switching to the deployment owned stage. afaics the change seems okay, as it effectively just changes out to create the new resource before destroying the old https://www.terraform.io/docs/configuration/resources.html#create_before_destroy

**Comment by kislyuk** [comment]
Custom domain names are indeed very commonly needed since that's the only way to get Lambda running on a domain name of one's choice (aside from ALB, which is not supported by Chalice and has other limitations).

> Also for customizations, rather than modifying the chalice output, you can just have a separate terraform file in the same directory, as terraform will compute its graph from all the directory (all files ending in tf and tf.json).

I am aware of that, @kapilt, and in fact you can see the separate `main.tf` file being created in the repro comment above (https://github.com/aws/chalice/issues/1237#issuecomment-531529984). It won't work for the `aws_api_gateway_deployment.rest_api` resource, though, because Chalice emits it, and it has to be edited in the Chalice-emitted TF code.

Adding support for custom domain names directly into Chalice will be tricky, since they require a manual step to verify the ACM certificate.

We have been using the configuration in https://github.com/aws/chalice/pull/1238 for several weeks of daily deployments now without any issues. Chalice+TF is unusable to us without that change.
