### ISSUE TITLE
Good practice of putting environment variable in global in unit testing

### ISSUE THREAD

**Issue by cftang0827** [aws/chalice#1292]
Hi, since I want to put some environment variables in global(e.g SQS path), and it works in both local mode and deploys mode, I guess it's because in cli there are some steps for importing environment variable.

However when I am writing unit test, I cannot import app well, it will show up cannot find the environment variable properly. 

Here's the sample in app.py
```python
app = Chalice(app_name='test')

s3 = boto3.client('s3')
dynamodb = boto3.resource('dynamodb')
sqs = boto3.resource('sqs')
clf = boto3.client('cloudfront')

queue = sqs.Queue(os.environ.get("SQS_URL"))
table = dynamodb.Table(os.environ['DYNAMODB_TABLE_NAME'])
```

And in unit test file, we cannot import the app

```python
import app

``` 

we will get an error because there's no "SQS_URL" environment variable. 

But in `LocalGateway`, we need app object
```python
local_gateway = LocalGateway(app, config)
```

**Is there any way we can get local gateway without sending app object?**
**Or it's not recommended to use an environment variable in global?** 

According to this issue (https://github.com/aws/chalice/issues/748)
it seems like the environment variable can only be got in the decorator. 

Also, I can define the environment variable before `import app` in the testing file, but I think it's not that good...

e.g.
```python
os.environ['S3_BUCKET_NAME'] = "XXXXXX"
import app
```

Thank you very much.

**Comment by stealthycoin** [comment]
What exactly are you unit testing? I wouldn't usually consider tests that test whole end to end requests, and require the full app to be set up, to be unit tests.

Normally I would expect there to be some class that uses the SQS queue, and it would take the URL as an initialization argument. Unit testing that class would just consist of passing some dummy value to that initializer, no need to import the app or use a LocalGateway at all. 

You can also write some form of OS interaction class like we have in Chalice [utils](https://github.com/aws/chalice/blob/master/chalice/utils.py#L118-L123). Every part of Chalice uses an instance of `OSUtils` to interact with the system. In tests we can just provide a class that fakes out the methods we need, but doesn't actually use the system environment. ([example here](https://github.com/aws/chalice/blob/8426d4c7f7df5588475e0b67ce8597278f4e9a1e/tests/unit/deploy/test_packager.py#L136-L137), [and here](https://github.com/aws/chalice/blob/8426d4c7f7df5588475e0b67ce8597278f4e9a1e/tests/unit/deploy/test_packager.py#L47-L52))

If you want to import the whole app and run full request/response lifecycle tests, and you want to use the acutal environment, you can use something like [pytest](https://docs.pytest.org/en/latest/monkeypatch.html) to mock out the environment, rather than setting it the way you were in your example.

**Comment by ilya-ibulaev-at-sloboda** [comment]
Hello

The same issue with new documented chalice testing guide: https://aws.github.io/chalice/topics/testing.html

It is ok, when I call os.env from lambdas, but the sample when I need ENV vars in decorator:

```python
import os
from chalice import Chalice, CognitoUserPoolAuthorizer

app = Chalice(app_name="transactions")

AUTH_COGNITO = CognitoUserPoolAuthorizer(
    os.environ["COGNITO_NAME"], provider_arns=[os.environ["COGNITO_PROVIDER_ARN"]]
)

@app.route("/", methods=["GET"], cors=foo, authorizer=AUTH_COGNITO)
def bar():
    return {"env_value": os.environ.get("COGNITO_PROVIDER_ARN")}
```

on testing raises key error:

```python
from chalice.test import Client
from app import app

def test_plaid_connection():
    with Client(app, stage_name="dev") as client:
        response = client.http.get("/")
        assert response.json_body == {
            "env_value": "...."
        }
```

How to solve this issue?
