### ISSUE TITLE
Connect to Dynamodb local for chalice local

### ISSUE THREAD

**Issue by rajpdus** [aws/chalice#1297]
Feature
=====
I believe chalice local by default can use other AWS resources which are configured for my AWS_PROFILE in that env. 

Since, most chalice apps are more of less CRUD apps. Does it make sense to have an option to connect to dynamodb local instance while running in local mode. Mostly needed when we are iterating over persisted models. 

Is there any way we can do that now?

**Comment by ricky-sb** [comment]
I don't think chalice comes with DynamoDB out of the box. I suppose you could conditionally update your boto3 config based on if chalice is running in local mode or not.  

@stealthycoin does chalice expose a variable when running in local mode? Or is there a way to tell when you're inside the app?

**Comment by jamesls** [comment]
There's no variable to specify when you're running in local mode.

It would also be great if you could specify a region per service, so in my `~/.aws/config` I could have something like:

```
[profile dev]
dynamodb = 
    region = local
```

The problem is, even if we wanted to support this, there's not a good way through global configuration (either `~/.aws/config` of env vars) to control a region for a specific service.  We could offer an API in chalice to do it, but then you'd have to use our API instead of the normal `boto3.client("dynamodb")`, which might not always be possible if your code doesn't control client creation.  Open to ideas,  we could just add an env var we set that says we're in local mode.

**Comment by rajpdus** [comment]
Yes agree there is no clean way of doing that. What I end up using is cloud formation to setup dynamo Tables for "local" environment as parameter. With a simple script I can update that stack and also the tables. I have a similar environment in chalice which with appropriate setting in chalice.config to point to those tables.

**Comment by jamesls** [comment]
Good to hear you have a solution that works for you.  I'm going to go ahead and close out this issue, but I'm open to ideas on how to improve this.
