### ISSUE TITLE
Support --dry-run option for deploy command

### ISSUE THREAD

**Issue by danil-smirnov** [aws/chalice#1341]
It would be great if I can check - if the last changes of my app are deployable, separately with the actual deployment.

Sometimes I'd like to complete my work by ensuring that no errors are raised by `chalice deploy` command, while I don't want to touch Dev/Prod environment yet.

I think that `--dryrun` switch should be supported as well (see [this issue](https://github.com/aws/aws-cli/issues/1965)).

**Comment by jamesls** [comment]
I agree.  I actually had a slightly different implementation of this that I never ended up sending a PR for that would go as far as figuring out what API calls to make and just printing (but not executing) the API calls.

It depends on what you mean by "is deployable."  We can ensure that everything from *our end* looks good, i.e we were able to load all the configuration, import your app correctly, and we can print a list of API calls we'd make in order to deploy your app.  But if you want to know whether or not those API calls will actually succeed, that becomes a lot more challenging because there's not really a good way to know that (aside from maybe we can check if IAM permissions allow for these calls?).

Let me know what you had in mind.

**Comment by danil-smirnov** [comment]
Thanks @jamesls !
For me even simple syntax/build check would be enough, but robust approach with API calls displayed, which you have just described, looks much better!

**Comment by ricky-sb** [comment]
>I actually had a slightly different implementation of this that I never ended up sending a PR for that would go as far as figuring out what API calls to make and just printing (but not executing) the API calls.  

I'm curious what the implementation for this looked like? We're currently using [pytest-chalice](https://github.com/studio3104/pytest-chalice) along with `chalice local` to test our API endpoints.

**Comment by jamesls** [comment]
I'll clean up the branch and send a PR for it today.  I think it's really helpful to have as a debugging tool.

**Comment by jamesls** [comment]
There's now a `chalice dev plan` that will show the API calls that will be made.  Let me know what you think.

**Comment by danil-smirnov** [comment]
Thank you @jamesls!
`chalice dev appgraph` is totally amazing :))
