### ISSUE TITLE
How to set lambda function name instead of using format <project_name>_<stage>_<handle_func>

### ISSUE THREAD

**Issue by finneon** [aws/chalice#1368]

**Comment by jamesls** [comment]
Chalice uses this naming convention to help organize resources based on the app and stage.  You can override the `<handle_func>` but otherwise there's no option to change the other part of the name when using `chalice deploy`.

If you use cfn to deploy your app (via `chalice package`), you can provide your own template of overrides that inject a function name in the cfn resource.  You can then specify that file via `--merge-template`.

**Comment by ofekfeller-glossai** [comment]
@jamesls How can I override the handle_func part and keep only the "project_name_stage" part?
