### ISSUE TITLE
SQS FIFO Support

### ISSUE THREAD

**Issue by amarjandu** [aws/chalice#1384]
Hey! I saw on the readthedocs that FIFO SQS queues are not supported by chalice yet, was there something preventing the integration? 
See:
https://chalice.readthedocs.io/en/latest/topics/events.html#sqs-events

**Comment by jamesls** [comment]
Initially it was because lambda didn't support this, but it looks like as of a few months ago this is now possible (https://aws.amazon.com/blogs/compute/new-for-aws-lambda-sqs-fifo-as-an-event-source/).  I'll check on this in the morning, it might just be some extra config options we need to add to support this, but this should be possible now.

**Comment by britishbadger** [comment]
> Initially it was because lambda didn't support this, but it looks like as of a few months ago this is now possible (https://aws.amazon.com/blogs/compute/new-for-aws-lambda-sqs-fifo-as-an-event-source/). I'll check on this in the morning, it might just be some extra config options we need to add to support this, but this should be possible now.

Hi James, Any update to this one ?

**Comment by jamesls** [comment]
Just verified, everything is working as expected.  The only real difference you'll see in terms of the event/API is that there's now a messageGroupId and a dedupeId.  It might be worth adding an `attributes` property so you can easily access the groupid/dedupeid but other than that everything works.

I'll update the docs to reflect this.
