### ISSUE TITLE
Context casts everything as str

### ISSUE THREAD

**Issue by fernandoflorez** [aws/chalice#1386]
Hello,

I'm setting a boolean on an AuthResponse context dict and all values are set to str.

return AuthResponse(routes=['*'], principal_id='user', context={'test': True})

Then:

return {'ret': app.current_request.context.get('test')}

// return is {"ret": "true"}

**Comment by jamesls** [comment]
Chalice doesn't modify the context values you provide, but it appears that the behavior you're seeing is caused by the service behavior of API Gateway.  From their [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-output.html):

>  You can access the stringKey, numberKey, or booleanKey value (for example, "value", "1", or "true") of the context map in a mapping template by calling $context.authorizer.stringKey, $context.authorizer.numberKey, or $context.authorizer.booleanKey, respectively. The returned values are all stringified. Notice that you cannot set a JSON object or array as a valid value of any key in the context map.

I'll add a note in our documentation about this behavior.
