### ISSUE TITLE
README still signals that no version > 3.7 is supported but 3.8 is supported after PR #1318

### ISSUE THREAD

**Issue by devangmehta123** [aws/chalice#1394]
See PR #1318

**Comment by jamesls** [comment]
Thanks, I'll get that updated.

**Comment by devangmehta123** [comment]
thx @jamesls . 

I also noticed one thing. I do not see an obvious place where the release model is described. For example, I would not file this issue if I thought that the PR is closed but still not released (as it turns out, it was released or is in the queue for release?).

There is one more place where 3.7 is mentioned, I think, contributions.rst.

I would like to contribute directly through PRs, even if it as as simple as writing documentation and I was looking for the release model.

For example, will a minor release automatically happen if the code is merged to master and the build passes all the tests? Do you use semantic versioning? 

And so on....

**Comment by jamesls** [comment]
We don't have a fixed release schedule.  I try to start releases whenever there's changes to release but there's not automatic release on every commit.

Docs are a little different.  While they're not part of a release in terms of a pypi package, they are automatically updated on readthedocs as soon as they're merged to master, so if you send a doc PR, it'll automatically get deployed once it's merged.

Otherwise our CHANGELOG shows what's been released.  If it's not in there yet then it hasn't been released.  Hope that helps, and feel free to send PRs!

**Comment by jamesls** [comment]
Addressed in https://github.com/aws/chalice/pull/1395.  Let me know if you have any more questions!
