### ISSUE TITLE
`chalice package` improvement proposals

### ISSUE THREAD

**Issue by devangmehta123** [aws/chalice#1423]
Here are a few observations I have made w.r.t. `chalice package`. These are not criticisms. It works great but it could do with some more advanced packaging.

One of them is in a separate issue already and marked by @jamesls .

1. Put deployment.zip in s3 object url specified and link to that inside chalice.tf.json for terraform packaging (in separate issue and already noticed by @jamesls )

2. It would help not to have to type the packaging options on the command line. They could be defaulted inside `.chalice/config.json`.

3. Support for automatic layer creation during `chalice package`. For example, my `app.py` contains API gateway entry points and only one event bridge entry point. It leads to a single lambda for the API gateway and a separate one for the event bridge entry point. But 99% of the code is shared inside `chalicelib/`. Currently, each of them has completely separate zip files deployed with all the code duplicated.

**Comment by jamesls** [comment]
Thanks for the feedback, I appreciate it.

For (2) are you saying you'd like a config option so you don't have to type out the `--pkg-format terraform` each time correct?  If so I think that's a reasonable feature request.

For (3), there's a PR that's lost a little steam (https://github.com/aws/chalice/pull/1179) but it's still something I plan on implementing.  We had to do some prerequisite work in order to make automatic layer creation possible, but I think it would be really helpful to support it.

To help track things, there are separate tracking issues for each of these features (I created one for feature 2):

1. https://github.com/aws/chalice/issues/1412
2. https://github.com/aws/chalice/issues/1424
3. https://github.com/aws/chalice/pull/1179

Let me know if you have any more feedback.
