### ISSUE TITLE
Compatibility with FastAPI

### ISSUE THREAD

**Issue by alarivarmann** [aws/chalice#1427]
Is it possible to integrate Chalice with FastAPI so that I could develop an API with FastAPI and deploy it using Chalice?

**Comment by jamesls** [comment]
This is not possible with Chalice.  It would be challenging to implement given we have to maintain backwards compatibility with the existing API Chalice provides, which isn't the same as FastAPI.

The other challenging part is that we still have to support python2.7 and FastAPI is py3 only so we wouldn't be able to directly integrate even if we were able to work around the backwards compatibility issues.

That said, I do like the features of FastAPI.  Maybe there's some way we could pull in some of its features or at least have similar APIs where possible.

**Comment by ricky-sb** [comment]
Probably the best two features of FastAPI are its docs generation and model validation. There's some discussion about model validation in this repo (https://github.com/aws/chalice/issues/1224), and there's even an [external project](https://github.com/jsfehler/leangle) to add model validation.  

[Docs generation](https://fastapi.tiangolo.com/tutorial/body/#automatic-docs) would be the cherry on top. Chalice already does some documentation generation because you can export an OpenAPI YAML file from API Gateway, so perhaps automating that process and allowing you to deploy it to a static site would be a good feature here.

**Comment by ricky-sb** [comment]
@jamesls can we re-open this? I'd love it if we could integrate FastAPI's docs-gen and modeling into chalice.

**Comment by NomeChomsky** [comment]
Request to reopen this ticket. The automatic documentation would be great - the docs tool is a great way to test the API as you develop. Data validation would also be great.

**Comment by rahulakash** [comment]
+1

**Comment by eyehint** [comment]
+1

**Comment by nyck33** [comment]
+1 fastapi too please :)

**Comment by jyrive** [comment]
+1

**Comment by davidolmo** [comment]
+1

**Comment by jayhack** [comment]
+1

**Comment by luiztauffer** [comment]
+1reopen

**Comment by saifullah-N** [comment]
+1 please 💯

**Comment by sagardevl** [comment]
+1
