### ISSUE TITLE
Use of vendored requests from botocore

### ISSUE THREAD

**Issue by andrew-mcgrath** [aws/chalice#1432]
https://github.com/aws/chalice/blob/5d28c0ea55fc7db12c536d0789c6707e8cd51c41/chalice/awsclient.py#L29-L32

The `botocore` team announced that they would no longer be vendoring requests inside of their package.  <https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/>

The documentation declares when upgrading to 1.11.0 that is especially import when depending the exception classes.  <https://botocore.amazonaws.com/v1/documentation/api/latest/index.html#upgrading-to-1-11-0>

With the `setup.py` requiring `botocore>=1.12.86,<2.0.0` won't this result in errors?

**Comment by jamesls** [comment]
> With the setup.py requiring botocore>=1.12.86,<2.0.0 won't this result in errors?

This *should* still be backwards compatible, but we should update the `awsclient` code to no longer use those exceptions (as its own standalone PR).

When we removed our vendored version of requests, we still kept the exceptions from requests around so that anyone catching those exceptions wouldn't see any breaking changes.  The way we did it was to create a new exception type that we raise that also subclasses from the vendored requests exception classes ([for example](https://github.com/boto/botocore/blob/develop/botocore/exceptions.py#L109)).  That way you can upgrade your code without having to also upgrade botocore's version.

**Comment by andrew-mcgrath** [comment]
@jamesls thanks for the clarification.
