### ISSUE TITLE
Chalice deployed resources in AWS Console?

### ISSUE THREAD

**Issue by grutty** [aws/chalice#1443]
I'm troubleshooting a "missing authentication token" error that seems to be coming from Cloudfront. I'm expecting in my AWS Console to find the resources chalice creates but API Gateway and Lambda functions are all empty, and CloudFront shows no usage. I do see an IAM that was created with the project name-dev but that's it. 

Should I expect to see the resources Chalice creates in my console? 

<pre><code>
< HTTP/2 403 
< content-type: application/json
< content-length: 42
< date: Tue, 23 Jun 2020 04:27:37 GMT
< x-amzn-requestid: dfea424c-e245-42ee-8315-af2dd87188a8
< x-amzn-errortype: MissingAuthenticationTokenException
< x-amz-apigw-id: OkGs_H6EvHcF6jw=
< x-cache: Error from cloudfront
< via: 1.1 4c7c693b007dfce603c83f138e31bccb.cloudfront.net (CloudFront)
< x-amz-cf-pop: SEA19-C2
< x-amz-cf-id: 0eO8CKJ7uuoX7sCvcA_gjFssmuWw5TZ0fRaPIJZOvbXftHcHHy3dUQ==
</code></pre>

**Comment by jamesls** [comment]
Yes you should.  The cloudfront headers you're seeing are due to the fact that API gateway uses cloudfront as part of its rest APIs (at least for the EDGE type), but we don't actually create a cloudfront distribution in your account.  I'd double check that you're looking at the correct region in your console (IAM is global which is why you'd see the resources no matter what).  You can also check the output of `.chalice/deployed/dev.json` which will contain a list of resources it created when it deployed. your app.

**Comment by grutty** [comment]
Thank you James! You can close this one.
