### ISSUE TITLE
Issue using dataclasses.asdict in response body

### ISSUE THREAD

**Issue by rickbhardwaj** [aws/chalice#1494]
Hi, 

Btw, I love Chalice. I ran into an issue where I tried to have a body variable in my response as follows:

```
@app.route('/private/users', cors=CORS_CONFIG)
def get_user():
    user_dicts = [dataclasses.asdict(user) for user in users.list_users()]

    return Response(
        status_code=201,
        headers=CORS_ENABLED_HEADERS,
        body=user_dicts
    )
```

User is a `@dataclass` file. It's pretty simple: 

```
from dataclasses import dataclass
from typing import List

from chalicelib.models.Message import Message


@dataclass(frozen=True)
class User:
    user_id: str
    sms_number: str
    email_address: str
    trusted_devices: List[str]
    conversation_history: List[Message]

```

This works when I run `chalice local`. However, when I run `chalice deploy` and try to build, I get this message. 

```
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/symtable.py", line 95, in lookup
    flags = self._table.symbols[name]
KeyError: 'user_dicts'
```

Full error log here: [chalice_deploy_err.txt](https://github.com/aws/chalice/files/5106624/chalice_deploy_err.txt)

Replacing the body variable with an empty dict fixes the issue and I can run `chalice deploy`.

**Comment by rickbhardwaj** [comment]
FYI I'm running `chalice 1.16.0, python 3.7.3, darwin 19.4.0`

**Comment by jamesls** [comment]
I think I figured out what was causing this.  If I add a function using the same name, then Chalice will get confused because it doesn't realize the scope for the function is overriden.  So I can get it to fail if I add a `def get_user(): pass` before your sample code:

```
import dataclasses
from chalice import Chalice, Response

app = Chalice(app_name='policybug')


def get_user():
    pass


@app.route('/private/users')
def get_user():
    user_dicts = [dataclasses.asdict(user) for user in users.list_users()]
```

Working on a fix, but a quick workaround is to same the second function something different.

**Comment by subssn21** [comment]
This is really weird because I use dataclasses and asdict extensively throughout my project and I have never seen this before.

I have seen similar errors if I inadvertently name two routes with the same function name, which clearly won't work.

Is the dataclass in your app.py or a separate file in chalielib?

**Comment by jamesls** [comment]
I've got a fix for this here: https://github.com/aws/chalice/pull/1498.  We can leave this open until the PR is merged.

**Comment by rickbhardwaj** [comment]
Thanks so much!
