### ISSUE TITLE
Load custom chalice class local

### ISSUE THREAD

**Issue by muriloviana** [aws/chalice#1502]
The feature for running chalice local is pretty nice. However, I've had a issue to run a custom chalice class local. Let's get the following case:

I need a custom method in my chalice app, so I did:
```python
from chalice import Chalice

class CustomChalice(Chalice):
    def custom_method(self):
        # do something

app = CustomChalice(app_name="custom")
```

Cool, it works perfectly in the prod stage, but when I run it local the app does not have the `custom_method` because `LocalChalice` is a subclass of `Chalice` instead of `CustomChalice`.

My suggestion is to use the current chalice app class in local mode.

**Comment by jamesls** [comment]
This was originally how the local mode worked, but we had to update it in order to fix the race conditions from using a threaded server (see #759 and #1375).  I'm open to changing this to support custom subclasses as long as we're still able to preserve the thread safety from those patches for local mode.

**Comment by aalvrz** [comment]
Issue can be closed it seems.
