### ISSUE TITLE
botocore's LambdaContext returns wrong stage map on custom domains

### ISSUE THREAD

**Issue by fernandoflorez** [aws/chalice#1503]
Hello,

This is not related to chalice but botocore but I'm posting it here so we can have it documented and also figure out if chalice should implement something around it.

When the apigateway is published on a custom domain name and the stage mapped to something different, for example "dev" to "dev-aws" (dev-aws being the mapping on the custom domain) the event context still displays "dev" as the stage and so chalice websocket configure doesn't work. Mapping for the stage is optional also so the url formatting also fails.

Thanks!

**Comment by jamesls** [comment]
Thanks for reporting.  Can you clarify which attribute on the `LambdaContext` you're referring to that has the `dev` stage?  And are you talking about the Chalice `stage` (i.e what's in your `.chalice/config.json` file) or the API Gateway stage (the URL prefix that gets added to your routes)?

**Comment by fernandoflorez** [comment]
APIGateway stage. On the websocket event arg, if you print the stage received it displays the current apigateway stage event though the lambda is executed through a custom domain with a different stage.

**Comment by jamesls** [comment]
I spent some time looking into this, and I think I see what's going on.

The `requestContext` has the correct `domainName` and `stage` if you map a custom domain to a websocket api:

```
2020-10-02 19:17:59.370000 5389c8 'domainName': 'api.chalice-demo-app.com',
...
2020-10-02 19:17:59.370000 5389c8 'stage': 'test-new-stage'}}
```

However, the problem is that you can't use a custom domain to configure Chalice's `websocket_api`.  It always has to be the auto-generated one.

It looks like other people have run into this, and reverting back to the auto-generated API when creating the SDK client worked as expected (https://stackoverflow.com/questions/55756269/why-doesnt-my-api-gateway-websocket-send-responses-with-custom-domain-name-conf).  We should be able to grab the API id from the requestContext and the region from the SDK client and correctly construct the correct endpoint.
