### ISSUE TITLE
Chalice deploy hangs indefinitely

### ISSUE THREAD

**Issue by mcchong** [aws/chalice#1553]
Trying to deploy, and hangs indefinitely at "Creating deployment package"

requrements.txt:

```
boto3==1.9.130
chalice==1.9.1
flywheel==0.5.3
dynamo3==0.4.10
extra-idx-private-pkg==0.0.1
moto==1.3.8
pyathena==1.4.3
pytest==4.6.3
pandas==1.0.3
urllib3==1.25.2
```

**Comment by mcchong** [comment]
Seems like the extra idx (configured in pip.conf) is prompting for a password, causing the hang?

**Comment by mcchong** [comment]
Yeah that was it.  For some reason pip-19.2 didn't like the private package index I was using and was trying to prompt for a username/password instead of using the token I had configured.  Upgrading to pip-20.something fixes that issue for me, but honestly there was no way for me to figure out what the issue was until I accidentally hit a key while it was hanging and I got a "Password:.." prompt.  A bit frustrating tbh.

**Comment by jamesls** [comment]
Interesting.  The reason there's no output from pip while creating the deployment package is because we have to call out to pip via a subprocess as there's no python public API we can use.  We then have to capture stdout/stderr to check on the results/status of the command.  I think in that case the best option we have is to use the `--debug` flag to get a better idea of what's going on during packaging.  Not sure if there's much more we can do until we can stop using subprocess with pip.  I'm glad you were able to figure it out though.
