### ISSUE TITLE
Chalice API Gateway endpoint changes every time chalice deploy

### ISSUE THREAD

**Issue by mato2** [aws/chalice#1570]
API Gateway endpoint changes after redeploying application. Is there a way to not have it changed? I am referencing the url in another API and its a problem if it changes every time I deploy an update. Is there a better way of doing this or workaround?

**Comment by jamesls** [comment]
Can you tell me more about how you're deploying your app?  Are you running `chalice deploy` as part of a CI system?  The endpoint URL should not change if you are redeploying the application.  Chalice checks if you've already deployed a REST API and will reuse the existing API but it does rely on local files to track the state.

**Comment by mato2** [comment]
Hi ,
We’re deploying as pipeline job on AWS codebuild and codedeploy. The
endpoint url changes after every deploy.

**Comment by jamesls** [comment]
Following up from #1569 this is due to the fact that `chalice deploy` tracks the state of the resources it's deployed in a local file in `.chalice/deployed`.  When you use something like codebuild/travis, etc. then those local files don't persist across deployments.  

The recommended solution at that point is to use `chalice package` and deploy with cloudformation (https://aws.github.io/chalice/topics/cfn.html), that way the state of your resources is maintained by cloudformation.

Otherwise, if you want to use `chalice deploy`, you'll have to have some way to sync the `.chalice/deployed` directory across multiple invocations.  I haven't tried this myself, but you might be able to use [codebuild caching](https://docs.aws.amazon.com/codebuild/latest/userguide/build-caching.html) to automatically handle this for you, but I'd still recommend going the cloudformation route.

**Comment by alexanderdamiani** [comment]
I'm assuming there's no update on this as I still have the same issue with `chalice deploy`?

**Comment by kylerlaird** [comment]
Are there step-by-step instructions available?  I'm trying to use this:
https://aws.amazon.com/blogs/developer/configuring-custom-domain-names-with-aws-chalice/

`Traceback (most recent call last):
  File "/root/lambda00/root/projects/capstone_budget/venv/lib/python3.9/site-packages/chalice/deploy/planner.py", line 41, in resource_deployed_values
    return self._deployed_resources.resource_values(
  File "/root/lambda00/root/projects/capstone_budget/venv/lib/python3.9/site-packages/chalice/config.py", line 503, in resource_values
    raise ValueError("Resource does not exist: %s" % name)
ValueError: Resource does not exist: api_gateway_custom_domain`

**Comment by vvvhung** [comment]
hi, I followed the tutorial here: https://aws.github.io/chalice/tutorials/wschat.html. I run the command `chalice deploy` then a new endpoint create. If I run `aws cloudformation deploy --template-file out/template.yml \
    --stack-name ChaliceChat --capabilities CAPABILITY_IAM` it return: No changes to deploy and lambda was not updated.

**Comment by vvvhung** [comment]
Found it. I need to do packaging again.
