### ISSUE TITLE
Exposing commit-tag or commit-id to lambda

### ISSUE THREAD

**Issue by lucagherardi** [aws/chalice#1626]
Hi Everyone, 

We would like to have the commit-tag and/or the commit-id available in the lambda, to be able to track the software version running in the cloud.
I thought about using env variable and/or tags, but I'm not sure about how to set them programmatically.
What is the best practice when it comes about tracking SW version?

Thanks in advance,
Luca

**Comment by jamesls** [comment]
The only way to set them programatically would be to have something write to the `.chalice/config.json` file with the updated tag/env var information whenever a deploy happens.  Otherwise there's an existing feature request for "dynamic config" that would let you inject information at deploy time (https://github.com/aws/chalice/issues/1334).
