### ISSUE TITLE
Existing lamba trigger is removed when deploying a new lambda using existing code base

### ISSUE THREAD

**Issue by wonjoonSeolDH** [aws/chalice#1644]
Hello,

It appears that the existing lambda trigger is removed when we deploy a new lambda (By changing name) using the same code (One that already has deployment json file)

### Code snippet to recreate the issue:
original lambda name: 'simple-alimtalk' was already deployed and we changed the name to 'notiyo-simple-alimtalk' to deploy another lambda.

- original code: we simply changed the app name and deployed again:
![image](https://user-images.githubusercontent.com/65998019/107182190-a1710080-6a1f-11eb-9c4a-73832923d4e6.png)
- original lambda, it has lambda trigger before deploying the new code
![image](https://user-images.githubusercontent.com/65998019/107182203-a766e180-6a1f-11eb-896f-b7a2471ebf92.png)

- New lambda is created, and it sets SQS lambda trigger correctly.
![image](https://user-images.githubusercontent.com/65998019/107182253-bcdc0b80-6a1f-11eb-9e10-40198b96e26c.png)

- But chalice removes existing lambda trigger from the original lambda function (the original lambda still exists though) when it deploys the new lambda
![image](https://user-images.githubusercontent.com/65998019/107182240-b77ec100-6a1f-11eb-984b-8a46b311154f.png)

The expected behaviour is it would leave the already deployed lambda as is, but it appears that we would have to use Chalice stages in order to avoid this issue. Is this behaviour intended?

**Comment by jamesls** [comment]
Changing the entire application name is not something that's really common within a Chalice app, and it appears there's some ambiguity when this happens.

The guiding principle with deploying chalice is that your current application/source represents exactly Chalice should create, and anything not in the app/source code should be deleted (if Chalice previously created it).  So the expected behavior if you go from:

```
@app.on_sns_message('testtopic1')
def myhandler1(event): pass
```

to

```
@app.on_sns_message('testtopic1')
def myhandler2(event): pass
```

Is that chalice will create a `myhandler2` function, subscribe it to the `testtopic1` SNS topic, then delete the subscription to `myhandler1` and then delete the `myhandler1` function.  This is similar to what would happen if you were to rename a resource in a CloudFormation template.

However, the case of renaming an entire application is ambiguous because while it doesn't technically change the "logical" names of your app (i.e your python function name didn't change), it does change the physical name because we prefix the actual name with the name of the app.

I'd suggest not changing the name of the application for an app you've already deployed.  I think ideally we should detect this and error out if this happens.  Let me know if you have any questions.

**Comment by wonjoonSeolDH** [comment]
Thank you for detailed reply James, 

If Chalice compares existing resource and deletes its difference, shouldn't Chalice also delete the original lambda?
(IIn the above case simple-alimtalk-dev-simple_alimtalk) 

Because like you said, the physical name of the lambda function is now changed and the old reference no longer exists in the source code.

**Comment by jamesls** [comment]
> If Chalice compares existing resource and deletes its difference, shouldn't Chalice also delete the original lambda?

Potentially yes.  In some ways, Chalice's application name is intended to be similar to a CFN stack name, in which case deploying a whole new stack wouldn't necessarily delete the old stack.  I think perhaps in the future it would just be better to error out on application name changes.
