### ISSUE TITLE
add_environment_variable Function Name

### ISSUE THREAD

**Issue by cb17** [aws/chalice#1734]
How am I supposed to know _before_ I deploy my stack that the function name that I need to specify in add_environment_variable is "APIHandler"? I don't see a way to programmatically get that name.

**Comment by jamesls** [comment]
The `APIHandler` is a special case for REST APIs because one lambda function is used for API Gateway (largely because of legacy reasons).  It's documented in the [config file docs](https://aws.github.io/chalice/topics/configfile.html#lambda-specific-configuration), but not in the `add_environment_variable` method.  Aside from that the Lambda function names map directly from the python function names (and can be overridden by providing a `name` param in the decorator.
