### ISSUE TITLE
How to upgrade Linux dependencies?

### ISSUE THREAD

**Issue by serivas** [aws/chalice#1740]
I'd like to use Chalice to deploy a project that uses OpenSSL 1.1.1+, but AWS Lambda Linux images seem to be using OpenSSL 1.0.3k, so my lambda function ends up timing out with the following error:

```
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2k-fips  26 Jan 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required
```

How can I do this with Chalice?

**Comment by jamesls** [comment]
There's not a lot of options for upgrading packages in your Lambda runtime aside from using a [custom runtime](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html) (which Chalice doesn't support).  Otherwise depending on what library you're using that needs TLS 1.3 support maybe using something like [pyopenssl](https://urllib3.readthedocs.io/en/latest/reference/contrib/pyopenssl.html) could be an option.
