### ISSUE TITLE
Vend chalice.cdk on npm

### ISSUE THREAD

**Issue by straygar** [aws/chalice#1743]
We recently stumbled upon Chalice, when thinking of spinning up a Python service. So far, it's been fantastic!

However, our team tries to stick to using the Typescript flavour of CDK across all our packages, so I wanted to create a basic CDK Typescript app under `infrastructure`, but I couldn't find an AWS chalice package on NPM, that would include the `Chalice` construct that does all of the magic.

Am I missing something, or is the lib contain python-only CDK constructs, only available via pip?

**Comment by jamesls** [comment]
> Am I missing something, or is the lib contain python-only CDK constructs, only available via pip?

That's correct, this lib contains python-only CDK constructs that are built-in to the Chalice python package.  The main reason for this is that we use Chalice's python API's to configure/package the Chalice application, so the construct needs to be in python otherwise we'd a typescript->python bridge to access Chalice's packaging.
