### ISSUE TITLE
Chalice Built-in Athrozier package size is the same as the REST API

### ISSUE THREAD

**Issue by RGEv1L** [aws/chalice#1773]
Greetings,

I am using Chalice 1.23 along with python 3.7.11 and I have deployed my REST API on AWS. I was wondering why the demo_auth function that I am using as lambda authorizer is having the same size as my complete project? 

I have downloaded the demo_auth lambda function from the AWS console and it has all of my project files in it as well.
[
![123](https://user-images.githubusercontent.com/26308685/127047628-150fd016-9adc-46a6-ac28-964a123950d1.png)
](url)

**Comment by jamesls** [comment]
Chalice uses the same deployment package for every Lambda.  The auth and handlers are all in the same file so in order to create different packages, we'd have to know what dependencies to include only in the auth function, and you'd have to make sure you don't import any unnecessary imports at the module level.  Right now the best option is to use [automatic layers](https://aws.github.io/chalice/topics/packaging.html?highlight=layers#automatic-lambda-layers) so at least the files are only uploaded once.
