### ISSUE TITLE
Selective lambda function update

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#1842]
I have been using Chalice for a while. One of challenges is the deploy can be slow or be aborted outside of US. It will be great if the deploy only updates lambda if code is changed. Currently, it will update/upload all lambda functions even I only change one line of code.

**Comment by jamesls** [comment]
I agree this would be useful, but it's challenging to do because all the lambda functions are defined within a single code base, so we can't know for sure if a Lambda function didn't actually change.  For example, if you changed some module level variable that your Lambda function referenced, we'd need to update the lambda function even though the body of the Lambda function didn't change.

The best option we have is to use something like auto managed layers (https://aws.amazon.com/blogs/developer/using-aws-lambda-layers-with-aws-chalice/) so at least we're only updating the `app.py` and `chalicelib/` directory instead all the shared dependencies from the requirements.txt file (which is usually the slowest part if you have a lot of dependencies).
