### ISSUE TITLE
Question: Is Chalice being supported?

### ISSUE THREAD

**Issue by bondgeek** [aws/chalice#2015]
I notice that no PRs have been closed since Sept 2022 -- can we count on Chalice receiving continued support?  Or should we create our own fork if we want to continue to use it?

**Comment by FelipeRuizGarcia** [comment]
@bondgeek , I saw there is not new branches or updates...  @jamesls @stealthycoin  could you please grant us access to maintainers in this repo or should we fork it?  I would like  continue with this official repo ( PRs, bugs ... )

**Comment by hitrust** [comment]
I also think this question should be considered. 
I think maybe boto team may focus on boto and other things that only the team can reach, maybe just make outline for this repo, and review and approve the PRs, so we can contribute continually.

**Comment by jamesls** [comment]
Hi, sorry for the delay here.

We are reallocating more time for Chalice support for triaging issues, bug
fixes, and maintenance PRs.  Long term, we'd like to work towards a Chalice 2.0
that will allow Chalice to be more easily extended without requiring changes to
the core code.  This requires removing a number of old features that would otherwise
make this work unrealistic.  I don't have a specific timeline for Chalice 2.0 but
will be adding proposals updates as work proceeds (they'll have the label `v2`).

Going through the issues/PRs now, but if there's anything in particular we should look at,
let us know.

**Comment by bondgeek** [comment]
Thanks @jamesls That is good to hear.  I think Chalice is fabulous and would like to lean into it more -- we're not even fully using its current capabilities.  If there is a path to a Chalice 2.0, then that gives the comfort to have more people on the team learn to use it.

In terms of specifics for v2
> Going through the issues/PRs now, but if there's anything in particular we should look at,
let us know.

I would just beg you to start by thinking about the upgrade path for developers.  If upgrading to v2 is equivalent to moving to a new framework, then I will re-evaluate all alternative frameworks before upgrading.
