### ISSUE TITLE
Route handling

### ISSUE THREAD

**Issue by johntmyers** [aws/chalice#487]
I just wanted to make a suggestion on route handlers, it seems wasteful to me to have to re-define routes in order to handle different functionality for different HTTP methods. For example, the docs have:

```python
@app.route('/myview', methods=['POST'])
def myview_post():
    pass

@app.route('/myview', methods=['PUT'])
def myview_put():
    pass
```

From what I can tell the function names are arbitrary, my suggestion would be to allow implicit method support through explicit function names, examples being how https://falconframework.org/ does it using `on_get`, `on_post`, etc as function names within a Resource class.

**Comment by jamesls** [comment]
Thanks for the suggestion.  I think that type of api makes a lot of sense when you have a class associated with a view, as it's done in falcon or in django with [class based views](https://docs.djangoproject.com/en/1.11/ref/class-based-views/base/#view) because you have a small namespace where these handlers can come from (the instance methods of the class).  However, if it's just binding to a function as it's done in chalice, I think it's a little too implicit to have `arbitrary_names_here_<HTTP_METHOD>` shared across the entire module namespace.  Class based views would be interesting though.

I'm inclined to mark this out of scope for now, but if anyone else wants this feature, please feel free to +1.

**Comment by jamesls** [comment]
Closing out old issue, this has been marked out-of-scope for a while and hasn't had any recent activity.
