### ISSUE TITLE
Pure Lambda: support for SNS trigger

### ISSUE THREAD

**Issue by paul-rs** [aws/chalice#488]
We have a number of pure lambda functions that we deploy through chalice (@app.lambda_function).  

It would be good to be able to specify an sns trigger for the pure lambda function by specifying the sns arn (similar to [serverless sns events]( https://serverless.com/framework/docs/providers/aws/events/sns/))

`functions:
  dispatcher:
    handler: dispatcher.dispatch
    events:
      - sns: arn:xxx`

**Comment by stealthycoin** [comment]
I'll mark this as a feature request.

**Comment by wollerman** [comment]
Maybe this could be handled with a new decorator:
```
@app.sns(topic_arn='mytopic_arn')
```

**Comment by wollerman** [comment]
I'd be happy to work on this and submit a pull request. 

The biggest question in my mind is how the subscription would be created and/or destroyed. It seems like it could be something done on deploy/delete?

**Comment by wollerman** [comment]
@jamesls  you mentioned you are working on this in #604. Do you have another issue open for the work? I would be happy to try and help!

**Comment by BigChief45** [comment]
I think this feature resembles #516 a lot. Although I also like the idea of using decorators for handling SNS topics.

**Comment by jamesls** [comment]
Yep so the initial the plan is to first add support for the various event sources as new decorators.  These handle the linking of the resource to the lambda function (and associated policies) along with any code abstractions to make working with the event easier.  #516 comes into play where it can also create the resource for you.  So as an example, you can have:

```python
@app.on_sns_publish(topic_arn='arn:foo:...')
def handler(event):
   pass
```

This assume the SNS topic already exists, but chalice will handle creating the lambda function, subscribing the lambda function to the topic if needed, and updating any policies.  I'm working on a branch that adds support for the various event sources we've had requests for including sns, s3, kinesis, and sqs (once it officially launches).  The resources proposal in #516 means it would also create the SNS topic (or s3 bucket, kinesis stream, sqs queue, etc) for you.

**Comment by jamesls** [comment]
Status update, I have a tracking branch that has initial support for this feature here: https://github.com/aws/chalice/compare/master...jamesls:sns-events?expand=1

It still needs a bit of work before it's ready for a PR but it's available for people that want to try it out:

Here's the gist of how it works:

I've added a new decorator to the app object, `on_sns_message`.  The only sns param it accepts is the topic name.  Things like subscription attributes/filters.  SAM doesn't support them so we'd have parity issues if we supported them in the deployer (unless we drop down to cfn).  Example:

```python

from chalice import Chalice

app = Chalice(app_name='snstest2')


@app.on_sns_message(topic_name='mytopic')
def index(event):
    print("The subject is: %s" % event.subject)
    print("The message is: %s" % event.message)
    print("Raw message: %s" % event.to_dict())

```

Missing:

* Sweeper/deletion code path
* SAM template generation.  Although we will be able to support SAM because the subscription is a separate CFN resource.

There's also a bit of duplication that I want to clean up before sending a PR.

cc @kyleknap

**Comment by BigChief45** [comment]
@jamesls 

Does the decorator `@app.lambda_function` still need to be added as well? Also, what happens with the `context` function parameter?

**Comment by kyleknap** [comment]
@jamesls It looks good. I like keeping the amount of properties we expose small for now (i.e. just `message` and `subject`). It should work fine for the use case I was thinking. As for the `topic_name` parameter, will that be the parameter we use for managed resources? For [on_s3_event](https://github.com/aws/chalice/issues/855#issuecomment-394207579), it looks like we decided to name it `bucket` so we can potentially overload it with a managed resource when needed. Do we want to do the same for topics? The one downside in naming the parameter `topic` is that it is not obvious if you want the name or arn of the topic.


@BigChief45 No the `app.lambda_function` would no longer be needed. So if you take this pure lambda function that was hooked up to an SNS topic out of band of a `chalice deploy`:
```python
@app.lambda_function()
def handle_sns_message(event, context):
    message = json.loads(event['Records'][0]['Sns']['Message'])
    # Do something with this message
```
It could be translated to this:
```python
@app.on_sns_message(topic_name='my-topic')
def handle_sns_message(event):
    message = json.loads(event.message)
    # Do something with this message
```
Plus chalice will set up the lambda subscription to SNS and permissions for you. So you would not need to do it out of band of `chalice deploy`.

As to the `context`, I would assume it would not be exposed on the `event` object that gets passed in to start. However, we could expose the `context` as a property of the `event` object that gets passed in, if we want to in the future. But it sounds like it is not targeted for this initial launch. Feel free to chime in on if you think we should include it for the initial launch though.

**Comment by BigChief45** [comment]
@kyleknap 

Understood.

Regarding `context`. I am currently monitoring my Lambda functions using [Sentry](https://github.com/getsentry/sentry). Basically you a decorator exposed by its client like this:

```python
@app.lambda_function(name='foo')
@raven.capture_exceptions
def foo(event, context):
```
And it will automatically send all raised exceptions to a central monitoring system. The problem is when there is no `context` parameter declared in the function. The application will deploy successfully but the `@raven.capture_exceptions` decorator will crash at runtime. I can confirm this because I was trying to use it with [Scheduled Events](http://chalice.readthedocs.io/en/latest/topics/events.html#scheduled-events), which do not contain a `context` parameter.

Hence why I think it would be good to still expose `context` as `context`.

**Comment by dmulter** [comment]
FYI, SAM/CF supports SNS filter policies this past March. Really would love to see the SNS decorator expanded to support it.
