### ISSUE TITLE
Pip freeze to requirements.txt creates chalice deploy error on Python 3.6.1

### ISSUE THREAD

**Issue by kevinpaulconnor** [aws/chalice#491]
Steps to reproduce. Python 3.6.1 installed via homebrew on Mac OS 10.12.6, although the error seems to be reproducible with Python 2.7 as well:

1. Create a new python3 virtual environment and install chalice
$python3 -m venv ./env
$source ./env/bin/activate
$pip install chalice
(which installs typing as a dependency)

2. Create a new chalice project and deploy
$chalice new-project freeze-test
$cd freeze-test
$chalice deploy
(deploys correctly as expected)

3. Freeze current requirements and redeploy
$pip freeze > requirements.txt
requirements.txt is now:
 
```
botocore==1.6.5
chalice==1.0.1
click==6.6
docutils==0.14
jmespath==0.9.3
python-dateutil==2.6.1
six==1.10.0
typing==3.5.3.0
```

$chalice deploy

During deploy, this error shows up:

```
Could not install dependencies:
typing==3.5.3.0
You will have to build these yourself and vendor them in
the chalice vendor folder.

Your deployment will continue but may not work correctly
if missing dependencies are not present. For more information:
http://chalice.readthedocs.io/en/latest/topics/packaging.html
```

…then it hangs updating the lambda function.
With chalice —debug deploy, it hangs at:

`botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>`

after write errors like:

```
2017-08-23 08:31:27,251 - botocore.endpoint - DEBUG - ConnectionError received when sending HTTP request.
Traceback (most recent call last):
  File "{$Path}/env/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File “{$Path}/env/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "{$Path}/env/lib/python3.6/site-packages/botocore/awsrequest.py", line 130, in _send_request
    self, method, url, body, headers, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "{$Path}/env/lib/python3.6/site-packages/botocore/awsrequest.py", line 157, in _send_output
    self.send(msg)
  File "{$Path}/env/lib/python3.6/site-packages/botocore/awsrequest.py", line 242, in send
    return HTTPConnection.send(self, str)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 965, in sendall
    v = self.send(data[count:])
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 935, in send
    return self._sslobj.write(data)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 636, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out
```

Once the deploy gets into this bad state, nothing that I've tried short of deleting the app gets it deploying again, like removing the typing requirement from the file or removing the requirements.txt file altogether. 

Although the error references the typing module, removing typing from the frozen requirements.txt will still produce the error. Removing both typing and chalice from the frozen requirements, leaving a file like:

```
botocore==1.6.5
click==6.6
docutils==0.14
jmespath==0.9.3
python-dateutil==2.6.1
six==1.10.0
```
...will not produce the issue.

I'm very new to Chalice, so hopefully this isn't something idosyncratic about my environment. I should be able to work around this by freezing only specific packages. Thanks!

**Comment by stealthycoin** [comment]
Chalice uses `requirements.txt` is used to determine what third party packages to bundle up with application and deploy to lambda as documented [here](http://chalice.readthedocs.io/en/latest/topics/packaging.html#rd-party-packages).

By freezing your dev environment to `requirements.txt` you are telling it to ship everything in your dev environment to your lambda runtime environment, some of which can't easily be packaged such as `typing`. 

Removing typing from `requirements.txt` doesn't fix the issue because you left `chalice` in which takes typing as a dependency so you are not removing the dependency from what it tries to package since it finds all the transitive dependencies. If you would like to have development requirements then put them in something like `requirements-dev.txt`, those should be totally different from your `requirements.txt` which is what you want to end up in the deployed lambda function.

I am unable to reproduce the hanging issue. It just deploys without `typing` when I try to repro on Chalice 1.0.1

Hopefully thats enough to get you unstuck? You can also try deleting the contents of the `.chalice/deployments/` directory. Which should start you over from the ground state, at least with regards to packaging up your app. Let me know if you have any other questions or  if you have more details on how to repro the hanging.

**Comment by kevinpaulconnor** [comment]
Your suggested workflow with requirements-dev.txt makes a lot of sense and is the workflow that I'll use to maintain local package isolation. Deleting the contents of the deployments directory does get me unstuck in my case; I'm not sure why the deployment continues to hang, but given that the pattern that's producing the hanging is clearly not the right way to proceed, I'm not going to chase it any further. Thank you very much for your help!
