### ISSUE TITLE
Version of Python in the "Development Environment Setup"

### ISSUE THREAD

**Issue by Marcelo-Theodoro** [aws/chalice#526]
In the CONTRIBUTING file it says:

`Keep in mind that chalice is designed to work with AWS Lambda, so you should ensure your virtual environment is created with python 2.7, which is the version of python currently supported by AWS Lambda.`

But since Apr 18, 2017 AWS Lambda has support for Python 3.6.

Is this right or the CONTRIBUTING file is just outdated?

**Comment by jrowen** [comment]
Somewhat related, `chalice generate-pipeline` results in the following error when run with Python 3.6.
```
CodeBuild does not yet support python version 'python3.6'.
```
But running `chalice deploy` with a different version, e.g. Python 3.5, results in the following message.
```
 .chalice\venv\lib\site-packages\chalice\deploy\deployer.py:87:UserWarning: You are currently running python3.5, but the close
st supported version on AWS Lambda is python3.6
Please use python3.6, otherwise you may run into deployment issues.
```

**Comment by stealthycoin** [comment]
@Marcelo-Theodoro 
Yep that should include python 3.6 which is supported by Lambda, we just missed this reference when we updated all the docs.

@jrowen 
CodeBuild does not have a supported python 3.6 image. As of the time of this writing they have 3.5.2 as their most recent version, so our CloudFormation template cannot generate a build environment for a python 3.6 project right now.

If you use the `chalice deploy` process you are uploading to straight to Lambda, there is no reason to use a python 3.5 environment rather than a 3.6 environment which will match the lambda runtime exactly. So the error and warning are both correct.

**Comment by stealthycoin** [comment]
Closing since the docs were updated to include python 3.6.
