### ISSUE TITLE
Enable automatic version publishing of lambda functions on deployment

### ISSUE THREAD

**Issue by david-poirier-csn** [aws/chalice#530]
I'd like to make it possible to enable chalice to publish a version of the lambda function when it's created or updated. This option would be enabled by a boolean option in config.json called "lambda_version_publishing". If enabled, chalice would call the "publish_version" method of the boto lambda client on lambda function creation or update, setting the "description" param to a string representation of the current UTC date/time.

**Comment by stealthycoin** [comment]
Can you tell me a little bit more about your use case for this? Chalice can publish a large set of resources including multiple lambda functions an an API gateway REST API, as well as possibly event sources such as CloudWatch Events. The main use case I can see for this is rolling back your application, which is very useful since it would only roll back the lambda component(s) of the Chalice app. The app's resources would then possibly be out of sync, APIs in API Gateway that go nowhere etc... This is only going to get worse as we add more resource types to Chalice through #516.

The correct way at the moment to version your application would be to roll forward by running `chalice deploy` again, which will ensure all your resources are in sync. You can use your version control system to make tags for certain known good releases and you can simply check them out and redeploy to deploy an older version of the app.

**Comment by david-poirier-csn** [comment]
I was hoping to coax chalice into using the version/alias functionality in Lambda, alongside the stages functionality in API gateway, to end up with a single lambda + api combo that had multiple deployments in it at various stages. But I can see that chalice has its own way of doing things that doesn't quite match what I'm after, so I'll close this off. Thanks for the reply!

**Comment by davidhavenly** [comment]
The use case I have is that, in order to use provisioned concurrency, it's required to have a published version and (optionally) an alias that points to a non-$LATEST version.  There doesn't seem to be an easy way to enable Provisioned Concurrency with chalice at the moment.

**Comment by t-koyoyo** [comment]
> The use case I have is that, in order to use provisioned concurrency, it's required to have a published version and (optionally) an alias that points to a non-$LATEST version. There doesn't seem to be an easy way to enable Provisioned Concurrency with chalice at the moment.

This is a very big problem, I was planning to use chalice for business, but if I can't enable Provisioned Concurrency, I can't use it.

**Comment by Landom3562** [comment]
> The use case I have is that, in order to use provisioned concurrency, it's required to have a published version and (optionally) an alias that points to a non-$LATEST version. There doesn't seem to be an easy way to enable Provisioned Concurrency with chalice at the moment.

I am having the same issue right now. Is there any solutions available for this problem?
