### ISSUE TITLE
Issue Modifying API Gateway Authorizers

### ISSUE THREAD

**Issue by kevinpaulconnor** [aws/chalice#539]
A week or two ago, I created an authorizer on the API Gateway via a call like:

authorizer = CognitoUserPoolAuthorizer(
    'My Auth Name', header='Authorization',
    provider_arns=['my provider settings'])

In the meantime, I deleted and recreated the Cognito User Pool that was associated with this authorizer. I updated my provider_arns in the code and redeployed, expecting that the existing Authorizer would be updated. But it isn't-I had to go into the API Gateway panel and manually edit/delete the authorizer, then redeploy with chalice, before things started working again.

It's understandable that the existing resource isn't updated by "chalice deploy", although it would be nice to have that. But it would be better if the documentation was more explicit that changes in code to CognitoUserPoolAuthorizers that have already been created via chalice will not be updated on the API Gateway via further chalice deploys. Or, I wouldn't mind if the "chalice deploy" failed on encountering an authorizer on the gateway that is inconsistent with the authorizer specified in code--I lost a few hours to figuring out why my Auth calls weren't working this evening.

Thanks!

**Comment by stealthycoin** [comment]
This appears to be an issue with the API Gateway API itself. I have verified that we push up a correct swagger document and call the put_rest_api method with the correct arguments. There isn't really anything we can do here that I can think of since there isn't an error being thrown by the service for us to catch and do something with. There is currently a pretty big deployer re-write happening which you can monitor the progress of here #549, we will see if we can figure something out to get this working.

**Comment by kevinpaulconnor** [comment]
Thanks, I'll keep an eye on that issue. Feel free to close this issue if that is best.

**Comment by stealthycoin** [comment]
Feel free to open an issue with API gateway about this as well. Either in their [forums](https://forums.aws.amazon.com/forum.jspa?forumID=199) or open a [support ticket](https://console.aws.amazon.com/support/home#/).

I will close this out here as there is no action for us to track here.
