### ISSUE TITLE
Is there a way to make chalice respect corp proxy settings?

### ISSUE THREAD

**Issue by blacktop** [aws/chalice#54]
http_proxy
https_proxy

Thank you.

**Comment by JamieCressey** [comment]
Botocore already supports those environment variables so any call to AWS should honour them. Are you seeing a specific problem?

**Comment by blacktop** [comment]
You are right I am sorry, my admin didn't give me Lambda privs, however, it would just hang when I tried to deploy.  Which in the past has been it bouncing off the proxys.  Maybe, you could add a check for IAM lambda privs?

**Comment by jamesls** [comment]
Could you clarify what you're suggesting?  Not sure I understand.  Check if you have appropriate permissions to deploy before deploying?

**Comment by blacktop** [comment]
I was wondering if there are APIs exposed to chalice that it could use to give more verbose error messages when something goes wrong, like your IAM doesn't not allow lambda access?  If that is not exposed then nevermind?

**Comment by jamesls** [comment]
Oh I see.  The problem here is it's not always possible to know why a request is rejected.  A lot of times we get an unauthorized error from the service without any additional context, so *we (client side)* don't even know why the request didn't work.

Let me try out a few things and see if I can improve the errors here.

**Comment by jamesls** [comment]
Closing out old issue, the error messages have been improved in later versions of chalice (1.2.0).
