### ISSUE TITLE
How to approach continuous delivery?

### ISSUE THREAD

**Issue by KamuelaFranco** [aws/chalice#605]
Does `chalice deploy` have an equivalent in the AWS CLI? If you are setting up chalice on your continuous integration pipelines, what specific setup are you using? I'm trying to wrap my head around continuous delivery because I've been using chalice locally and loving it.

**Comment by kyleknap** [comment]
I would recommend taking a look at the `chalice generate-pipeline` command and its [documentation](http://chalice.readthedocs.io/en/latest/topics/cd.html). Chalice has tooling for setting a CD codepipeline so that all you need to do is push your code to your remote repository and it will run through your pipeline and end up deploying your chalice application. There is also working examples of this in the [chalice workshop](http://chalice-workshop.readthedocs.io/en/latest/part2/index.html) that I would suggest taking a look at. Let us know if that helps!

**Comment by jamesls** [comment]
Closing out issue, let us know if you have any more questions.
