### ISSUE TITLE
Bug report: Missing request body

### ISSUE THREAD

**Issue by gldavis3000** [aws/chalice#606]
Bug report: I recently got a new computer at my job so I had to reinstall chalice.  After deploying our api with the new version of chalice I noticed that every request body was being stripped out (anything other than GET that has no body of course).  I don't know exactly which part of the chalice process caused this to happen.  All I know is that when I did app.current_request.to_dict() to get the event it contained no '_body' or 'body'.  When I did pip install chalice on my new computer it installed version 1.0.4.  I reverted this back to 1.0.3 then 1.0.2 which both resulted in the stripped body.  When I reverted back to 1.0.1 the body showed up again.  I can continue working now, but I thought you should be aware of this.

**Comment by kyleknap** [comment]
I can confirm this. The change was made in this PR: https://github.com/aws/chalice/pull/506. That pull request has a lot of discussion related it to this removal. But to summarize, there was a bug inherently with having the `_body` and `_raw_body` in the result of `app.current_request.to_dict()` because the body did not have to be JSON serializeable and you would run into JSON loading errors if it was not serializeable. Furthermore, the value was prefixed with an underscore indicating that it was internal and generally should not have been used. In general, I would recommend using the `app.current_request.raw_body` to get the body of the request. Is there any particular reason that you were using `app.current_request.to_dict()` to get the body?

**Comment by gldavis3000** [comment]
Our company is a startup that wanted to move our data processing to AWS.  We contracted another company to setup our API, User Pool, etc. and that's what they did in the chalice lambda code.  Since no one in our company had any experience with this I had to learn everything from scratch after we took control of everything.  I just took it for granted that to_dict gave me what I needed and focused on more important things that needed to happen.  Thank you for explaining this to me so I can update our code.
