### ISSUE TITLE
Allow lambda settings outside of config.json

### ISSUE THREAD

**Issue by carlvitzthum** [aws/chalice#607]
From my understanding, the `lambda_timeout` and `lambda_memory_size` values in the config file will always apply to any lambdas generated by chalice. Obviously this includes the main lambda for the application, but also applies to lambdas created using scheduled events.

It would be nice to be able to overwrite lambda settings defined in the config file for such events. A use case could be a daily scheduled event that is expected to run all functions in your app and requires a longer timeout and/or more memory than an individual route in your app.

By the way, chalice is a pleasure to use. Thanks!

**Comment by jamesls** [comment]
Looks like we're missing docs here.  It's currently possible to have per-lambda configuration, but you have to still specify this in the config.json file.  For example, given this app:

```python
from chalice import Chalice

app = Chalice(app_name='demo')


@app.route('/')
def index():
    return {}


@app.lambda_function()
def foo(event):
    return {}
```

I can configure settings for the `foo` lambda function by using:

```
$ cat .chalice/config.json
{
  "stages": {
    "dev": {
      "api_gateway_stage": "api",
      "lambda_functions": {
        "foo": {
          "lambda_timeout": 120
	}
      }
    }
  },
  "version": "2.0",
  "app_name": "demo"
}
```

In other words, you can add a `lambda_functions` key, and within that key is a mapping of function name to config values.  In this case, my python function is named `foo` so that's the key name that I have to use.

Let me know if you have any more questions.  Labeling this a "documentation", we'll get this added to our docs

**Comment by carlvitzthum** [comment]
That's just what I was looking for. Thank you!
