### ISSUE TITLE
Chalice deploy fails in AWS China

### ISSUE THREAD

**Issue by SamMacedo** [aws/chalice#667]
Recently in Nov 2017 support for lambdas in China was announced:
https://www.amazonaws.cn/en/new/2017/aws-lambda-is-now-available-in-the-aws-china-beijing-region-operated-by-sinnet/

When trying to deploy a Chalice project to China, we get the following error message:

`An error occurred (InvalidParameterValueException) when calling the 
 CreateFunction operation: EnvironmentVariablesFeature is not supported in cn-
 north-1 region. For more information, please visit the AWS Lambda 
 documentation on Environment Variables.`

This is our config file:
`{`
`  "stages": {`
`    "dev": {`
`      "api_gateway_stage": "dev",`
`      "manage_iam_role": false,`
`      "iam_role_arn": "arn:aws-cn:iam::<ACCOUNT_NUMBER>:role/lambda-role",`
`      "lambda_timeout": 300`
`    }`
`  },`
`  "version": "2.0",`
`  "app_name": "my-project"`
`}`

Looks like Lambdas in China don't support environment variables and Chalice is always trying to set environment variables even thought we haven't defined any in the config file.

**Comment by kyleknap** [comment]
So what I think what is happening is that when Chalice is making the `CreateFunction` call it is providing an empty dictionary for the environment variables. Then, Lambda throws back an error saying it is not supported since Chalice provided it but is empty. We will look into seeing if we can relax this and instead do not always use an empty dictionary for the environment variables.

In the meantime, I would recommend trying out `chalice package` as a deployment option as it looks like it does not have that issue.

**Comment by SamMacedo** [comment]
Thanks! we will experiment with `chalice package` as an alternative in the meantime.

**Comment by stealthycoin** [comment]
Closing in favor of new issue.
