### ISSUE TITLE
chalice deploy -> removes caching settings

### ISSUE THREAD

**Issue by rafnarnason** [aws/chalice#703]
I have a local chalice api, a staging api on AWS and a production api on AWS, 

- every time I deploy to AWS my request path cache settings are removed making me have to do a lot of AWS console clicking and setting the same configuration up again - perhaps this could be declared somehow in the views? anybody know of some nifty workarounds?

**Comment by kyleknap** [comment]
This looks like a duplicate to: https://github.com/aws/chalice/issues/324. Currently when a chalice deploy happens it creates a swagger document that gets imported into API Gateway. By not including anything related to caching in the swagger document, API Gateway is clobbering any cache settings that you may have set through the console. So unfortunately, I do not think there really is any workarounds for this. Given there is a previous request for this, I would prefer to track this feature request in the previously referenced issue. Also feel free to comment or submit a proposal for this feature if you have any preference on how you would like to see caching exposed. Otherwise closing out this issue in favor of the other one.

**Comment by dperconti** [comment]
I've had the same issues. Looking forward to https://github.com/aws/chalice/issues/324 being implemented.
