### ISSUE TITLE
demo not working in china

### ISSUE THREAD

**Issue by fangde** [aws/chalice#777]
I just install the laster chalice and run the demo

Creating role: helloworld-dev
ERROR - While deploying your chalice application, received the following error:

 An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy 
 operation: Partition "aws" is not valid for resource "arn:aws:logs:*:*:*".

any suggestion for a quick fix?

**Comment by fangde** [comment]
i am using aws in the cn-north-1 regsion

**Comment by kadrach** [comment]
I assume this is because the ARN format is slightly different for China. In general, ARNs follow the pattern `arn:partition:service:region:account-id:resource`, where `partition` is `aws` for most of the world and `aws-cn` for China. It looks like the more common "arn:aws" is currently hardcoded in quite a few places.

**Comment by stealthycoin** [comment]
Closing in favor of new issue.
