### ISSUE TITLE
Secrets Manager not supported?

### ISSUE THREAD

**Issue by jpi-car** [aws/chalice#811]
Directly mirroring from https://github.com/awslabs/aws-sam-local/issues/367, I'm having issues with deploying my Chalice app when I try to use Secrets Manager. When deployed, the app errors out with this error: `module initialization error: Unknown service: 'secretsmanager'.` I tried following the suggestion in the provided link above by using pip wheel boto3, and then placing the generated pip wheels inside the vendor folder, however this didn't solve the issue.

**Comment by jpi-car** [comment]
@stealthycoin Ah, haha. Thank you very much. That was a silly mistake of me. Closing.

**Comment by ilyaGotfryd** [comment]
While this issue is closed pulling values from Secrets Manager at the time of the deployment to reside as environment variables with an instance of Lambda is a common place pattern. It would be a proper feature to implement. I run into this need literally with every new project I push into production.
Please reconsider this as a basic security requirement and not a frivolous want as indicated by response in this thread.
