### ISSUE TITLE
IAM policy: runtime.sagemaker is unsupported

### ISSUE THREAD

**Issue by juliensimon** [aws/chalice#816]
Hello,

it looks like Chalice 1.2.2 cannot auto generate an IAM statement for 'runtime.sagemaker'.

Example:
```
from chalice import Chalice
import boto3

app = Chalice(app_name='bug')

@app.route('/')
def index():

    sm = boto3.client('sagemaker')
    sm.list_endpoint_configs()

    rtsm = boto3.client('runtime.sagemaker')
    rtsm.invoke_endpoint()
```

```
$ chalice gen-policy
Unsupported service: runtime.sagemaker
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "sagemaker:ListEndpointConfigs"
      ],
      "Resource": [
        "*"
      ],
      "Effect": "Allow",
      "Sid": "55f7e9705e2848c39b8b8e533c93f2c2"
    }
  ]
}
```

**Comment by kyleknap** [comment]
@juliensimon 

Would it be possible to use the name `sagemaker-runtime` instead? So the `app.py` would look something like this:
```python
from chalice import Chalice
import boto3

app = Chalice(app_name='sage-maker')


@app.route('/')
def index():

    sm = boto3.client('sagemaker')
    sm.list_endpoint_configs()

    rtsm = boto3.client('sagemaker-runtime')
    rtsm.invoke_endpoint()
```
This works for me when I generate a policy:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "sagemaker:ListEndpointConfigs"
      ],
      "Resource": [
        "*"
      ],
      "Effect": "Allow",
      "Sid": "6a6b038e603a47db8c969057cf6eb03b"
    },
    {
      "Action": [
        "sagemaker:InvokeEndpoint"
      ],
      "Resource": [
        "*"
      ],
      "Effect": "Allow",
      "Sid": "73c4e8ba99434011bed8cde2060f61dd"
    }
  ]
}
```
The reason that I ask this is `runtime.sagemaker` is a hidden alias for `sagemaker-runtime`. We prefer that user's use `sagemaker-runtime` instead when instantiating the `boto3` client, and since it is a hidden alias, Chalice is unaware of it when generating the policy (which is why it is not doing so in your code snippet). Let us know.

**Comment by juliensimon** [comment]
OK, this works indeed. I'll use 'sagemaker-runtime' from now on :) Thanks for clarifying.

**Comment by samanvithaburle43** [comment]
Even i am facing with the same issue . When i am running the command sh post.sh , i am facing with an issue as " UnknownServiceError: Unknown service: 'sagemaker-runtime' ".
Though i changed the policies and also the service name as sagemaker to "sagemaker-runtime"
Please let me know if there is any solution to solve the error
