### ISSUE TITLE
Error generating Pipeline

### ISSUE THREAD

**Issue by d3prof3t** [aws/chalice#819]
I have a Python app with 3.6 runtime. Local and dev stages work like a breeze. But when moving onto the code pipeline generation seems like Code Build does not support the Python 3.6.
Please refer to the below paste link for detailed trace.

https://pastebin.com/bHWnMyGJ

**Comment by kyleknap** [comment]
Yeah it is unfortunate that CodeBuild does not have a built-in image for Python3.6. In order to work around this, a custom image needs to be supplied that runs on Python3.6. Here is a blog post on how you can create a [custom image](https://aws.amazon.com/blogs/devops/extending-aws-codebuild-with-custom-build-environments/) (note that is doing it for PHP) and the [Dockerfile used for Python3.5](https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/python/3.5.2) (you should be able to copy a fair amount of this while switching out the Python3.5 bits for Python3.6). Once that is set up, you can then supply code build image with the `--codebuild-image` to `generate-pipeline` to use it in your CodePipeline. Let us know if that helps or if you have any more questions.

**Comment by d3prof3t** [comment]
Sure will try to work with the custom image. But would really appreciate if AWS gets Python 3.6 runtime in CodeBuild.

**Comment by jamesls** [comment]
There's no official codebuild image for python 3.6.1 but you can use the official python image from dockerhub by providing the -i value if you don't want to use a custom image:

```
chalice generate-pipeline -i python:3.6.1 out.json
```

Let me know if you have any more questions.
