### ISSUE TITLE
Deploy error when not granted lambda:UpdateFunctionConfiguration permission

### ISSUE THREAD

**Issue by mvermaes** [aws/chalice#820]
Should it be possible to deploy Lambda functions without granting the `lambda:UpdateFunctionConfiguration` IAM permission? Our use case is that we would like to be able to:
- deploy Lambda functions and API endpoints via Chalice
- allow these functions to access resources in our private VPC, by associating them with specific subnets and security groups in the VPC (to access RDS)
- prevent the modification/creation of Lambda functions such that they become associated with non-Lambda designated subnets/security groups

AWS Support suggested the above could be achieved by disabling the `lambda:UpdateFunctionConfiguration` permission. This seems to work from the AWS Console (code can be edited in the web editor, and access to the VPC functionality is disabled. Unfortunately it means that `chalice deploy` no longer functions:

```
$ chalice deploy
Creating deployment package.
Updating lambda function: testing-dev
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/chalice/cli/__init__.py", line 357, in main
    return cli(obj={})
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/chalice/cli/__init__.py", line 142, in deploy
    deployed_values = d.deploy(config, chalice_stage_name=stage)
  File "/home/user/.local/lib/python2.7/site-packages/chalice/deploy/deployer.py", line 344, in deploy
    raise ChaliceDeploymentError(e)
ChaliceDeploymentError: ERROR - While deploying your chalice application, received the following error:

 An error occurred (AccessDeniedException) when calling the 
 UpdateFunctionConfiguration operation: User: arn:aws:iam::123456789012:user
 /xyz is not authorized to perform: 
 lambda:UpdateFunctionConfiguration on resource: arn:aws:lambda:ap-
 southeast-1:123456789012:function:testing-dev
```

This happens both when creating or updating an existing function, using the 'hello world' example code. Chalice version is 1.2.2.

Let me know if you need more details, or if you have pointers on where I can look in the code to see why this permission is needed (I haven't had any luck finding it from a quick look around).

**Comment by kyleknap** [comment]
The permission is mainly needed for updating configurations such as environment variables, memory size, and lambda timeouts. It is interesting that you are running into this when creating lambda functions. I would have expected it only happens for updating lambda functions. The tricky part about it is that in order to get this to work, there needs to be more granularity with IAM policies (i.e. deny `lambda:UpdateFunctionConfiguration` for Vpc configuration parameters and not just all parameters). It may be possible to add a flag to not update the function configuration or have the deployer be smarter about when it actually needs to make an `UpdateFunctionConfiguration` call. The only downside is that you would never be able to update properties such as environment variables, memory size, and lambda timeouts.

I think one option maybe worth exploring is to be a little more granular with the roles that you are using. So for those trying to use the console, they would have a role with `lambda:UpdateFunctionConfiguration` denied, and then for those using chalice, they could use a different role that would include permissions to `lambda:UpdateFunctionConfiguration`. Another to note is that Chalice does not support VPC configuration as of now. So deploying with chalice should not affect it. However, that may change once we do support VPC's (but it would be exposed through configuration nonetheless).

Let us know your thoughts on these options.

**Comment by mvermaes** [comment]
Not sure what's up with the bot, since I did respond :) But I understand if there's not really much that can be done to enable this scenario currently.

**Comment by joguSD** [comment]
@mvermaes VPC support was recently added. Though, I don't think a release has been cut for it yet.

Also, if you're just using chalice as a deployment tool you might also want to look at the `chalice package` command, which can produce cloudformation templates for you:
https://chalice.readthedocs.io/en/latest/topics/cfn.html

You might also be interested in the base CD pipeline chalice can spin up for you (which uses chalice package):
https://chalice.readthedocs.io/en/latest/topics/cd.html

Let me know if any of this helps.
