### ISSUE TITLE
Confused http error

### ISSUE THREAD

**Issue by wutachih** [aws/chalice#830]
When the token expires, it returns internal error (500) instead of (400). Should we add code in jwt_auth to respond clearer error code?

**Comment by jamesls** [comment]
Are you saying that in your custom authorizer, if the jwt token is expired you get a 500 instead of a 400?  If the code is in your custom authorizer it would probably be best to catch the jwt auth errors and return an `AuthResponse` that says that the auth request failed.

If you have a code sample I can try out, I might be able to give you a code snippet that fixes the issue.
