### ISSUE TITLE
Skip Lambda Environment Supported Python Packages in Deployment Package

### ISSUE THREAD

**Issue by wollerman** [aws/chalice#843]
This is a feature request. 

I'm not sure if this functionality is always desired, but I noticed a difference while testing different combinations. The python 2.7 lambda environment already has boto3 available. So deploying a blank chalice app creates a package size of ~17K. However, when adding `boto3==1.3.1` to `requirements.txt` the size jumps up to 3.9MB. 

```
$ ls -lrth .chalice/deployments
-rw-r--r--  1 matt  staff    17K May 16 12:56 d41d8cd98f00b204e9800998ecf8427e-python2.7.zip
-rw-r--r--  1 matt  staff   3.9M May 16 12:56 781c6a4faff7afef80aeca0d4f1495c4-python2.7.zip
```

Based on this, maybe chalice could provide a flag to ignore lambda pre-built packages? This way packages can be specified in requirements.txt normally and when it duplicates what exists in the lambda environment, lambda size can be kept minimal. 

Obviously there are more details to think through. I just wanted to throw the idea out there.

**Comment by jamesls** [comment]
Hi, thanks for the feature request.  I think it's an interesting idea, but I don't know how feasible this is to implement.  Some issues I see:

* The version of boto3 (and its dependencies) are updated periodicallyin lambda.  While we could try to keep a hardcoded list the latest boto3 version in lambda, we would have no idea if it was correct.  The only way to know for sure if to create a lambda function and check what version of boto3 is installed, which seems challenging to add to the existing deployment process.
* We'd have to take boto3's transitive dependencies into account when building our deployment package.  This again will depend on what version of boto3 we're targeting.  As a recent example, one transitive dependency of boto3 is (`boto3 -> botocore -> dateutils`).  botocore had a max upper bound of `<2.7.0` on dateutils, which was intentionally not the latest version.  If, in your requirements of your chalice app you had `python-dateutil>2.0,<=3.0`, then pip would chose 2.7.3, the latest version because it isn't able to see the `python-dateutil<2.7` that comes from botocore.

Curious what others think.

**Comment by wollerman** [comment]
Ah, that's unfortunately. My biggest unknown was lambda policy on publishing what's available in the environment. That process is completely opaque? [This page](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html) suggests it's available in an AMI but again that seems to be opaque. 

Does boto provide any sort of query-able endpoints with environment data? I see [get_account_settings()](http://boto3.readthedocs.io/en/latest/reference/services/lambda.html#Lambda.Client.get_account_settings) but that obviously isn't the correct information.

**Comment by jamesls** [comment]
Closing out old issue.  As far as I know there's nothing you can query to find that information so there's not much we'd be able to do in Chalice until then.
