### ISSUE TITLE
issue with `chalice local` version 1.3.0

### ISSUE THREAD

**Issue by tahayk** [aws/chalice#857]
I recently upgraded from chalice `1.2.3` to `1.3.0`, 
but when I run `chalice local`, I keep getting this messages and all my **POST** requests fail (GET request works fine):
```
Found credentials in shared credentials file: ~/.aws/credentials
Serving on 127.0.0.1:8000
Restarting local dev server.
Serving on 127.0.0.1:8000
Restarting local dev server.
```

I'm using:
- python 3.6.0
- os: windows 7 & ubuntu 16.04

**Comment by jamesls** [comment]
Hi, could you share a set of steps that demonstrate the issue?  It seems to be working for me.  Here's what I tried:

```
$ chalice new-project foo
$ cd foo/
$ # Edited my app.py to have this:
$ cat app.py
$ cat app.py
from chalice import Chalice

app = Chalice(app_name='foo')


@app.route('/')
def index():
    return {'hello': 'world'}


@app.route('/post', methods=['POST'])
def posttest():
    return app.current_request.to_dict()

$ chalice local

$ # GET request works:
$ http localhost:8000
HTTP/1.1 200 OK
Content-Length: 18
Content-Type: application/json
Date: Fri, 01 Jun 2018 20:36:49 GMT
Server: BaseHTTP/0.3 Python/2.7.14

{
    "hello": "world"
}

# POST request works:
 $ echo '{"foo": "bar"}' | http POST localhost:8000/post
HTTP/1.1 200 OK
Content-Length: 420
Content-Type: application/json
Date: Fri, 01 Jun 2018 20:37:22 GMT
Server: BaseHTTP/0.3 Python/2.7.14

{
    "context": {
        "httpMethod": "POST",
        "identity": {
            "sourceIp": "127.0.0.1"
        },
        "path": "/post",
        "resourcePath": "/post"
    },
    "headers": {
        "accept": "application/json, */*",
        "accept-encoding": "gzip, deflate",
        "connection": "keep-alive",
        "content-length": "15",
        "content-type": "application/json",
        "host": "localhost:8000",
        "user-agent": "HTTPie/0.9.9"
    },
    "method": "POST",
    "query_params": null,
    "stage_vars": {},
    "uri_params": {}
}

```
And in the `chalice local` window I see:

```
127.0.0.1 - - [01/Jun/2018 13:36:49] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Jun/2018 13:37:22] "POST /post HTTP/1.1" 200 -
```

**Comment by tituskruse1** [comment]
i have a similar issue.. it fails when i call the second internal function on my app to clean a pandas dataframe. running the script via if __name__ works perfect. 

Windows 10
Python 3.6
Git Bash terminal

Restarting local dev server.
Serving on 127.0.0.1:8000
Found credentials in shared credentials file: ~/.aws/credentials
Starting new HTTPS connection (1): neptunebucketman.s3.us-west-2.amazonaws.com
Restarting local dev server.
Serving on 127.0.0.1:8000
Found credentials in shared credentials file: ~/.aws/credentials
Starting new HTTPS connection (1): neptunebucketman.s3.us-west-2.amazonaws.com

**Comment by zaibacu** [comment]
I'm getting same issue when downloading file from s3

OS: OpenSuse Tumbleweed, Kernel: `4.17.12-1-default`
Python 3.6

VirtualEnv:
```
attrs==17.4.0
boto3==1.7.72
botocore==1.10.72
chalice==1.6.0
click==6.7
docutils==0.14
enum-compat==0.0.2
jmespath==0.9.3
python-dateutil==2.7.3
regex==2018.7.11
s3transfer==0.1.13
six==1.11.0
typing==3.6.4
```

```
import boto3
from chalice import Chalice

app = Chalice(app_name='article-classifier')

MODELS_BUCKET = 'classifier-models'

s3 = boto3.resource('s3')

bucket = s3.Bucket(MODELS_BUCKET)

BASE_PATH = os.path.dirname(os.path.realpath(__file__))
LIBS = os.path.join(BASE_PATH, 'cache', 'libs.zip')

@app.route('/ping')
@libs_wrapper
def ping():
    try:
        bucket.download_file(Key='libs.zip', Filename=LIBS)
    except Exception as ex:
        logger.error(ex)
    return {'result': 'pong'}
```

Console output:

```
Found credentials in shared credentials file: ~/.aws/credentials
Serving on 127.0.0.1:8000
Restarting local dev server.
Found credentials in shared credentials file: ~/.aws/credentials
Serving on 127.0.0.1:8000
Starting new HTTPS connection (1): classifier-models.s3.us-east-2.amazonaws.com
Starting new HTTPS connection (2): classifier-models.s3.us-east-2.amazonaws.com
Starting new HTTPS connection (3): classifier-models.s3.us-east-2.amazonaws.com
Restarting local dev server.
Found credentials in shared credentials file: ~/.aws/credentials
Serving on 127.0.0.1:8000
```

**Comment by renatodmb** [comment]
I have the same issue, any solution into it?

**Comment by maybebored** [comment]
@zaibacu I faced the same issue, because I was saving the files downloaded from s3 into a folder in my project directory. **Chalice local restarts automatically when it detects changes in the project directory, so make sure your program doesn't modify anything in the project directory while running.** Maybe this insight might help you or others.

**Comment by luisfontes19** [comment]
I'm getting the same issue (not related to #1064 which is a constant loop)

Im using `chalice 1.27.3, python 3.11.0, linux 5.15.49-linuxkit` on docker with an M1

For me it happens every time I write to DynamoDB (I'm using PynamoDB). So I'm only writing on post/put/delete methods, and thats why it doesn't happen for example on GET. Not sure if thats the case with the user that opened this issue.

The dynamo database is in a different container so it can't be reloading for a change in the db file. 

Also, i created a simple node script to watch for file changes in the same folder as chalice and it didn't detect and change while chalice restarted.

I don't seem to have any error and the the request that was received goes through properly before the server gets restarted so it cannot be due to a file change.

I would appreciate some guidance here 😁

**Comment by hamishfagg** [comment]
@luisfontes19 did you ever figure this out? Same issue on m1 mac docker, but this only happens sometimes. Causes malformed HTTP responses which break my tests locally.

**Comment by hamishfagg** [comment]
On further investigation you can see if chalice thinks a file has changed when running `chalice --debug local`

In our case pytest was writing cache files which triggered the restart

**Comment by luisfontes19** [comment]
@hamishfagg I eventually found out yes. 

In my case was a series of mistakes 😅

The dynamoDB folder from the other container was inside the chalice project folder although I had it previously configured somewhere else, something went wrong there. Chalice then noticed the change in files every time I did a post because i was in fact writing to the DB which was inside the chalice project folder

Didn't find out why the script I wrote didn't catch the changes inside that folder, but at this point is irrelevant...

Thanks for the tip of the `--debug` flag, I was trying to understand which files triggered the change, but i didn't see in the logs, and didn't notice the debug option. Good to know
