### ISSUE TITLE
Documentation on CORS for multiple origins

### ISSUE THREAD

**Issue by sbassi** [aws/chalice#950]
According to the documentation at https://github.com/aws/chalice#tutorial-cors-support, 

"If you need to supply multiple origins you will need to define a custom handler for it that accepts OPTIONS requests and matches the Origin header against a whitelist of origins. " 

then there is an example that does not accept OPTIONS. Part of example:

```
@app.route('/cors_multiple_origins', methods=['GET'])
def supports_cors_multiple_origins():

```
 Is the example wrong or the rest of the documentation wrong?
Algo, the route wrapper has no cors parameter there, and the documentation states that "Every view function must explicitly enable CORS support."

I think both issues should be addressed in the documentation.

**Comment by stealthycoin** [comment]
Issue one looks like an oversight, the OPTIONS parameter should be included. I can get that added. 

As for the other issue I'm not sure what you mean, looks correct to me. Essentially you have to roll it yourself because API gateway has a static configuration, so as soon as you need something that differs based on the content of the request you need to do it yourself, which is what the example shows.

**Comment by sbassi** [comment]
@stealthycoin Thank you for the changes. One more question. The doc states: "If the match is successful then return just their Origin back to them in the Access-Control-Allow-Origin header."
But in the OPTION you are sending all origins instead of just the one that matches.

`','.join(_ALLOWED_ORIGINS)`

if this OK? Sending only one is for the other methods?
